### ISSUE TITLE
[Visium HD 3' beta support] Spatial subsetting issue

### ISSUE THREAD

**Issue by YoukaiFromAccounting** [satijalab/seurat#10070]
This issue is a continuation of this comment on Visium HD 3' support here:

- https://github.com/satijalab/seurat/pull/10028#issuecomment-3244291423

_Originally posted by @BioinfSina in https://github.com/satijalab/seurat/issues/10028#issuecomment-3244291423_

- - -

I have been trying to subset the zebrafish head dataset to only the eye area. 
Plotting the tissue coordinates I got this overview:
<img width="1224" height="812" alt="zebrafish_head" src="https://github.com/user-attachments/assets/bf49dc06-f431-4c0c-b15b-c28704198645" />

Using this I estimated my eye to be between  200<x<400 and 100<y<250. That does not return the expected area though, instead get's me this:
<img width="1224" height="812" alt="zebrafish_eye_expectedcoords" src="https://github.com/user-attachments/assets/ab9720aa-f533-4703-a5ed-e31565ed8262" />

I realised the x coordinates were fine, but the y coordinates seem incorrect. After playing around with y coordinates I found that this code gave me the results I wanted:

`tissue <- GetTissueCoordinates(v3d, image = "slice1.polygons")`

`tissue_filtered <- tissue[tissue$x>=200 & tissue$x<=400 & tissue$y>=250 & tissue$y<=400, ]`

`cropped_cells <- tissue_filtered$cell`

`eye <- subset(v3d, cells = cropped_cells)`

`SpatialFeaturePlot(eye, images = "slice1.polygons", features = "nCount_Spatial.Polygons", plot_segmentations = TRUE, crop = TRUE) 
`

Resulting in this cropped subset:
<img width="1224" height="812" alt="zebrafish_eye_adaptedCoords" src="https://github.com/user-attachments/assets/546765c7-034b-4a17-97b9-db7eb063afc2" />

That doesn't match the previously plotted coordinates though. I had used this code to plot the full dataset:
`SpatialDimPlot(v3d, images = "slice1.polygons",pt.size.factor = 0.1, plot_segmentations = FALSE) +`
  `theme(axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 12, color = "black"),
        axis.title.y = element_text(size = 12, color = "black"),
        axis.line = element_line(color = "black"),
        axis.ticks = element_line(color = "black"),
        panel.border = element_rect(color = "black", fill = NA))`

Is there a bug in how the y coordinates are saved or plotted?

**Comment by YoukaiFromAccounting** [comment]
Hello @BioinfSina, thank you for your message. The tissue coordinates on the overview should be correct; if I run:

```{R}
#Defined zebrafish eye regions
x_crop <- c(200, 400)
y_crop <- c(100, 250)

#Plot using SpatialDimPlot
SpatialDimPlot(
  object = v4d,
  images = "slice1.polygons",
  alpha=0.5,
  plot_segmentations = TRUE,
  stroke = 0.1,
  crop = TRUE
) +
  coord_sf(
    xlim = x_crop,
    ylim = y_crop,
    expand = FALSE
  )
```

I am able to get the subset region of the eye:

<img width="498" height="331" alt="Image" src="https://github.com/user-attachments/assets/6a1607de-c44d-47a9-8c60-15a4848e371d" />

Could you possibly verify by rerunning the Spatial plotting commands in a fresh R session? It could be that a previous coordinate system is overriding the coord_sf cropping functionality.

**Comment by BioinfSina** [comment]
I dod get the same behaviour you get when using your code, but I need to subset the sample and that does not work with the expected parameters. It seems GetTissueCoordinates results don't overlap with plot coordinates - even though I am using GetTissueCoordinates because in another issue someone suggested this attempt for creating subsets (plot with a grid, define parameters, subset with the help of GetTissueCoordinates).

**Comment by YoukaiFromAccounting** [comment]
@BioinfSina Ah yes, I see the issue now, apologies for misunderstanding your original question. There appears to be a y-scaling mismatch between the actual coordinates retrieved by GetTissueCoordinates (based on spot centroids) and the segmentation coordinates for the spatial polygons. We are currently working to address this; thank you for catching this!

**Comment by anashen** [comment]
@BioinfSina thank you for reporting this issue! This has been resolved in the PR created by @YoukaiFromAccounting at #10082, which I have just merged into the spaceranger-4.0 branch.

Please be sure to restart your R session after reinstalling the branch from GitHub, and feel free to follow up with any questions. Thanks!

**Comment by BioinfSina** [comment]
Unfortunately with the most recent version of the branch the issue is back - the coordinates now seem to have a minimum of over 3000 and the plot I get with 

`SpatialDimPlot(v3d, images = "slice1.polygons",pt.size.factor = 0.1, plot_segmentations = FALSE) +
theme(axis.text.x = element_text(size = 10, color = "black"), axis.text.y = element_text(size = 10, color = "black"), axis.title.x = element_text(size = 12, color = "black"), axis.title.y = element_text(size = 12, color = "black"), axis.line = element_line(color = "black"), axis.ticks = element_line(color = "black"), panel.border = element_rect(color = "black", fill = NA))`

is not helpful to filter coordinates at all.

**Comment by YoukaiFromAccounting** [comment]
Hello @BioinfSina, thank you for your message,

With the update of the main branch to include support for objects with segmentations, we have made the decision to move away from using coordinates to subset Spatial plots for now, as we realized even previous Visium V2 and Xenium objects would also encounter issues with coordinate alignment. Due to the inconsistencies with coordinate systems used by all these spatial objects, we don't anticipate officially recommending or supporting coordinate-based subsetting/cropping for the future, though this may change depending on user interest. 

For now, we recommend to use InteractiveSpatialPlot for the purposes of subsetting spatial objects, which should work just as well as coordinate-based subsetting.

**Comment by BioinfSina** [comment]
That unfortunately doesn't work either. It looks like the cells are turned 90 degrees to the slide, so I don't know what part of it to trust to select cells.

**Comment by YoukaiFromAccounting** [comment]
@BioinfSina The rotated cells are the correct ones, the tissue slide image is plotted independently of the coordinate system, so currently it will always be plotted upright. We're currently exploring options to to fix this.

**Comment by anashen** [comment]
This should be fixed now with #10254 from @YoukaiFromAccounting; please reinstall from GitHub to see the changes:

```R
devtools::install_github("satijalab/seurat", ref = "main", force = TRUE)
# restart R session
# packageVersion("Seurat") should show 5.4.0.9004
```

Make sure you have SeuratObject v5.3.0 as well.

Please feel free to update here with any issues or questions!
