### ISSUE TITLE
BUG: Error: ! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct.

### ISSUE THREAD

**Issue by chichen24601** [satijalab/seurat#10250]
### Issue Description

Hi Seurat team,

I'm trying to run BANKSY on a 10x Visium HD dataset (binned at 8µm, assay named "Spatial.008um") using `SeuratWrappers::RunBanksy()` as part of the Seurat Visium HD analysis vignette, but it fails immediately with the following error that "Error: 
! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct. "

### Reproducing Code Example

```R
> packageVersion("Seurat")
[1] ‘5.3.1.1000’
> packageVersion("SeuratObject")
[1] ‘5.3.0’

> object <- RunBanksy(object,
+                     lambda = 0.8, 
+                     verbose = TRUE,
+                     assay = "Spatial.008um", 
+                     slot = "data", 
+                     features = "variable",
+                     k_geom = 50
+ )

Fetching data from slot data from assay Spatial.008um
Error: 
! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct.
ℹ Please use the `layer` argument instead.
Run `rlang::last_trace()` to see where the error occurred.
```

### Error Message

```shell

```

### Session Info

```shell
> sessionInfo()
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 17763)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

time zone: Asia/Tokyo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] remotes_2.5.0        Banksy_1.5.10        SeuratWrappers_0.4.0 Matrix_1.7-0         sf_1.0-23            dplyr_1.1.4         
 [7] patchwork_1.3.2      ggplot2_4.0.1        Seurat_5.3.1.1000    SeuratObject_5.3.0   sp_2.2-0            

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3          rstudioapi_0.17.1           jsonlite_2.0.0              magrittr_2.0.4             
  [5] magick_2.9.0                spatstat.utils_3.2-0        farver_2.1.2                zlibbioc_1.52.0            
  [9] vctrs_0.6.5                 ROCR_1.0-11                 spatstat.explore_3.6-0      S4Arrays_1.6.0             
 [13] htmltools_0.5.9             SparseArray_1.6.2           sctransform_0.4.2           parallelly_1.46.0          
 [17] KernSmooth_2.23-22          htmlwidgets_1.6.4           ica_1.0-3                   plyr_1.8.9                 
 [21] plotly_4.11.0               zoo_1.8-14                  igraph_2.2.1                mime_0.13                  
 [25] lifecycle_1.0.4             pkgconfig_2.0.3             rsvd_1.0.5                  R6_2.6.1                   
 [29] fastmap_1.2.0               aricode_1.0.3               GenomeInfoDbData_1.2.13     MatrixGenerics_1.18.1      
 [33] fitdistrplus_1.2-4          future_1.68.0               shiny_1.12.1                digest_0.6.39              
 [37] S4Vectors_0.44.0            tensor_1.5.1                RSpectra_0.16-2             irlba_2.3.5.1              
 [41] GenomicRanges_1.58.0        sccore_1.0.6                progressr_0.18.0            spatstat.sparse_3.1-0      
 [45] httr_1.4.7                  polyclip_1.10-7             abind_1.4-8                 compiler_4.4.0             
 [49] proxy_0.4-28                withr_3.0.2                 S7_0.2.1                    DBI_1.2.3                  
 [53] fastDummies_1.7.5           R.utils_2.13.0              MASS_7.3-60.2               DelayedArray_0.32.0        
 [57] rjson_0.2.23                classInt_0.4-11             tools_4.4.0                 units_1.0-0                
 [61] lmtest_0.9-40               otel_0.2.0                  httpuv_1.6.16               future.apply_1.20.1        
 [65] goftest_1.2-3               R.oo_1.27.1                 glue_1.8.0                  dbscan_1.2.3               
 [69] nlme_3.1-164                promises_1.5.0              grid_4.4.0                  Rtsne_0.17                 
 [73] cluster_2.1.6               reshape2_1.4.5              generics_0.1.4              gtable_0.3.6               
 [77] spatstat.data_3.1-9         R.methodsS3_1.8.2           class_7.3-22                tidyr_1.3.1                
 [81] data.table_1.17.8           XVector_0.46.0              BiocGenerics_0.52.0         spatstat.geom_3.6-1        
 [85] RcppAnnoy_0.0.22            ggrepel_0.9.6               RANN_2.6.2                  pillar_1.11.1              
 [89] stringr_1.6.0               spam_2.11-1                 RcppHNSW_0.6.0              RcppHungarian_0.3          
 [93] later_1.4.4                 splines_4.4.0               lattice_0.22-6              survival_3.5-8             
 [97] deldir_2.0-4                tidyselect_1.2.1            SingleCellExperiment_1.28.1 miniUI_0.1.2               
[101] pbapply_1.7-4               gridExtra_2.3               IRanges_2.40.1              SummarizedExperiment_1.36.0
[105] scattermore_1.2             stats4_4.4.0                Biobase_2.66.0              matrixStats_1.5.0          
[109] UCSC.utils_1.2.0            stringi_1.8.7               lazyeval_0.2.2              codetools_0.2-20           
[113] tibble_3.3.0                BiocManager_1.30.27         cli_3.6.5                   uwot_0.2.4                 
[117] leidenAlg_1.1.5             xtable_1.8-4                reticulate_1.44.1           GenomeInfoDb_1.42.3        
[121] Rcpp_1.1.0                  globals_0.18.0              spatstat.random_3.4-3       png_0.1-8                  
[125] spatstat.univar_3.1-5       parallel_4.4.0              mclust_6.1.2                dotCall64_1.2              
[129] SpatialExperiment_1.16.0    listenv_0.10.0              viridisLite_0.4.2           scales_1.4.0               
[133] ggridges_0.5.7              e1071_1.7-16                crayon_1.5.3                purrr_1.2.0
```

**Comment by anashen** [comment]
Hi @chichen24601,

Thanks for the report -- the calls to `GetAssayData` and `SetAssayData` in `RunBanksy` (from SeuratWrappers) still use the `slot` parameter (had been deprecated in SeuratObject v5.0.0 since Oct 2023, now defunct). 

We will fix this very soon in [SeuratWrappers](https://github.com/satijalab/seurat-wrappers); a quick fix until then would be to downgrade `SeuratObject`.

**Comment by anashen** [comment]
Hi @chichen24601,

This has now been fixed via https://github.com/satijalab/seurat-wrappers/pull/223. Please install the latest version of SeuratWrappers, and be sure to restart your R session afterwards.

```R
remotes::install_github("satijalab/seurat-wrappers", force = TRUE)
```

**Comment by ssukumaran2** [comment]
Hi,
I am having the same issue with RunALRA command. Sueratwrappers was updated and R  was restarted, but the issue is not resolved. I am using seurat 5.4.0.

``` 
CVMoFacs<-RunALRA(CVMoFacs, layer='data')
Error:
! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is
  now defunct.
ℹ Please use the `layer` argument instead.
Run `rlang::last_trace()` to see where the error occurred.

> packageVersion("SeuratObject")
[1] ‘5.3.0’
> packageVersion("Seurat")
[1] ‘5.4.0’
```

**Comment by anashen** [comment]
Updating the issue for others to add that RunALRA is also fixed; see https://github.com/satijalab/seurat-wrappers/issues/225.

- - -

> [!NOTE]  
> Make sure to use `layer` instead of `slot` in calls to `GetAssayData`, `SetAssayData`, etc. to avoid the error in your packages / workflows that use Seurat. (Params / functions deprecated in SeuratObject `v5.0.0` (Oct 2023) had been scheduled for eventual defunction after 3 releases.) If there are problematic calls in SeuratWrappers, please open a new issue and we will work to fix it ASAP. Thank you!

**Comment by chichen24601** [comment]
RunBanksy() now works. Thank you very much!
