### ISSUE TITLE
CalcVarExpRatio throws error when using more than 20 dimensions

### ISSUE THREAD

**Issue by symbiologist** [satijalab/seurat#138]
Hi Seurat team,

Thanks for an awesome 2.0 update! I've been playing with the new alignment alignment feature and following the tutorial here: http://satijalab.org/seurat/Seurat_AlignmentTutorial.html

I was interested in trying higher number of dimensions for CCA and set the num.cc = 30 in RunCCA and dims.use = 1:30 in CalcVarExpRatio. However, I get the following error:

**Error in GetGeneLoadings(object = object, reduction.type = reduction.type,  : 
  Could not find the following dimensions: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30**

There are no errors if I use 20 dimensions or less. I copied and pasted the code from the tutorial exactly, except for the two changes I mentioned above. The two changes, specifically, are:

pbmc <- RunCCA(object = tenx, object2 = seqwell, genes.use = hvg.union, **num.cc = 30**)
pbmc <- CalcVarExpRatio(object = pbmc, reduction.type = "pca", grouping.var = "protocol", **dims.use = 1:30**)

Not a huge deal as I'm sure 20 dimensions is sufficient for most applications, but thought I would report this as I have some complex datasets where I'd like to test higher dimensions of CCs to compare in CalcVarExpRation.

Thanks!

David

**Comment by satijalab** [comment]
Good catch, thanks! We'll fix in an upcoming release on the develop branch.

**Comment by jprestonnn** [comment]
I am very interested in running higher dimensions as well... please update if any progress has been made on this issue. Thanks!

**Comment by igordot** [comment]
Did this get fixed? I am seeing the error in 2.1 (from CRAN).

**Comment by andrewwbutler** [comment]
This should be fixed now on the develop branch.

**Comment by jprestonnn** [comment]
Awesome!! Thanks

**Comment by jprestonnn** [comment]
Hello,

I'm still getting the same error. Woud you mind confirming that I am correctly installing the new development branch? Session info is pasted below, and here is my code for uninstalling/ reinstalling Seurat, followed by an attempt to run CalcVarExpRatio with more that 20 dimensions:

remove.packages("Seurat")
install.packages("devtools")
library(devtools)
install_github("satijalab/seurat", ref = "develop",force = TRUE)
library(Seurat)

...

$ N21_OH1 <- RunCCA(object = N2_1, object2 = OH_1, group.by = "sample", scale.data = TRUE, rescale.groups = TRUE)
$ N21_OH1 <- CalcVarExpRatio(object = N21_OH1, reduction.type = "pca", grouping.var ="sample", dims.use = 1:30)

"Calculating for N2_1 
	 Separating N2_1 cells
	 Running Dimensional Reduction 
Error in GetGeneLoadings(object = object, reduction.type = reduction.type,  : 
  Could not find the following dimensions: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30"

...

SessionInfo:

R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.3 (Maipo)

Matrix products: default
BLAS: /gpfs/packages/R/3.4.2/lib64/R/lib/libRblas.so
LAPACK: /gpfs/packages/R/3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] bindrcpp_0.2        Seurat_2.1.0        Biobase_2.36.2     
[4] BiocGenerics_0.22.0 Matrix_1.2-11       cowplot_0.9.0      
[7] ggplot2_2.2.1       devtools_1.13.4    


Thanks!!

**Comment by andrewwbutler** [comment]
If you want to run `CalcVarExpRatio` on more than 20 dims, you need to specify at least that many in the `RunCCA` call. Try modifying your first line to be 

`N21_OH1 <- RunCCA(object = N2_1, object2 = OH_1, group.by = "sample", scale.data = TRUE, rescale.groups = TRUE, num.cc = 30)`

**Comment by jprestonnn** [comment]
Thank you!!! It works beautifully now.
