### ISSUE TITLE
The Idents() factor levels disordered after IntegrateData

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1529]
Hi Seurat team :
    I found that when after integrate the big data, the levels( Idents(scObject) ) sometimes disorder.  One of my data sets is about 2.3w cells. After IntegrateData, the order of levels( Idents(scObject) )  is like 0, 1, 2, 3,..... . While another data set is about 7.0w cells. After IntegrateData, the order of levels( Idents(scObject) )  is like 0, 1, 10, 11,.....2, 20, 21 .....
    I check many time. Even I know that I can change by myself. While I cant  supply my data sets its too big. I still hope you can check that if there is a problem that the levels of factor will disorder after integrate.

Best

**Comment by gcday** [comment]
I've noticed this in a similar context--specifically when GroupSingletons finds one or more singletons during clustering. It seems that particular function's use of as.character might be to blame? The fix I use at the moment (called just after GroupSingletons in FindClusters). 
`clustering.results[, paste0("res.", r)] <- factor(type.convert(x = as.character(x = clustering.results[, paste0("res.", r)])))`

**Comment by SeadonXing** [comment]
Yes I agreed with @gcday . I also found this factor level disorder is coupled with  singletons identified. BTW whats the "singletons" mean in the FindClusters ?

**Comment by andrewwbutler** [comment]
What exactly is the issue here? That the factor levels aren't numerically increasing? You can reorder them to ensure that ordering with:

```R
Idents(object) <- factor(x = Idents(object), levels = sort(levels(object)))
```

@SeadonXing , a singleton is just a cluster that is made up of a single cell.

**Comment by SeadonXing** [comment]
Yes, @andrewwbutler . I can use the command to reorder the factor level of idents. Its not a big problem. I just want to know that why sometimes the order of idents is following by numerically increasing, while sometime disordered.

**Comment by andrewwbutler** [comment]
This should be resolved now on the develop branch. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by cramirezs** [comment]
> This should be resolved now on the develop branch. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

I got version 3.0.2 and it is not resolved. It has caused some issues with the FindAllMarkers function because, after reassigning the identities, the clusters are mixed.
