### ISSUE TITLE
Error loading H5AD file from ScanPy (different issue from below)

### ISSUE THREAD

**Issue by RoganGrant** [satijalab/seurat#1690]
I am attempting to load .h5ad files generated in Scanpy from the following figshare directory: https://figshare.com/articles/Processed_files_to_use_with_scanpy_/8273102 . When I load any of the "droplet" files with `ReadH5AD()`, I get the following output. Is this potentially an issue with the Scanpy metadata? I don't see a clear reason in the source code why this would occur. Thanks!

> Pulling expression matrices and metadata
Data is unscaled
Merging feature-level metadata dataframes
Creating assay object
Storing X as data and raw as counts
Setting highly variable features
Error in tolower(x = selection.method) : 
  argument "selection.method" is missing, with no default

**Comment by MediciPrime** [comment]
Glad its not just me, I am having the same problem!!  I was able to use this function in the past when Seurat v3 wasn't officially out but some type of recent change has resulted in this error.  

Please help!

**Comment by lijxug** [comment]
Same issue here

**Comment by zzwch** [comment]
Is there any way bypass this error?

**Comment by satijalab** [comment]
Apologies for the delay, we are looking into this now

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by guangli0817** [comment]
But the conversion has replaced the annotation information such as mouse.id in the dataset with numbers, could you fix that? Thanks.

**Comment by sergiopolid** [comment]
Hello, I'm still having this issue, have this been fixed? I have the development version and is not working neither.

**Comment by arutik** [comment]
Hello,

Seems like it's not fixed, I'm having the same issue after installing the development version.
