### ISSUE TITLE
mean.function and dispersion.function in FindVariableFeatures

### ISSUE THREAD

**Issue by astrovsky01** [satijalab/seurat#2189]
When running the following code
```
FindVariableFeatures(object = seuset,
                                       selection.method = "mvp",
                                       mean.function = ExpMean,
                                       dispersion.function = LogVMR
                                       )
```
I keep getting the error
```
Error in mean.function(object, verbose) : unused argument (verbose)
```
This is the same for dispersion.function when mean.function and dispersion.function are traded.

**Comment by timoast** [comment]
Hi, thanks for reporting! I'm able to reproduce this and will work on a fix soon

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by alwhiteh** [comment]
Hi, I installed the development version of Seurat, but am still having this issue. 

I'm trying to update this code from previous Seurat versions:
`All_MFs2 <- FindVariableGenes(object = All_MFs2, mean.function = ExpMean, dispersion.function = LogVMR, do.plot = TRUE, x.low.cutoff = 0.0125, x.high.cutoff = 1.5, y.cutoff = 0.5)`

And I think the analogous code for the most recent version of Seurat would be:All_MFs2 <- `FindVariableFeatures(object = All_MFs2, selection.method = 'mvp', mean.function = ExpMean, dispersion.function = LogVMR, nfeatures = 2000, mean.cutoff = c(0.0125,1.5), dispersion.cutoff = c(.5,30), verbose = TRUE)`

Am I doing something else wrong?
