### ISSUE TITLE
Error in RenameCells

### ISSUE THREAD

**Issue by camerongw** [satijalab/seurat#3183]
Hi, I'm currently trying to add a new assay into an existing Seurat object and need to rename the cells before doing so. I'm getting an error as you can see below. I import the object:

```
> mono
An object of class Seurat
56164 features across 20706 samples within 2 assays
Active assay: SCT (22626 features, 3000 variable features)
1 other assay present: RNA
5 dimensional reductions calculated: vae, umap, vae_nobc, umap_nobc, vae_2dims
```
Then gsub to remove an old identifer that I no longer need before checking that the number of unique cell names is unchanged:
```
> mono_names <- rownames(mono@meta.data)
> mono_names <- gsub("d21_1017_","",mono_names)
> length(unique(mono_names))
[1] 20706
```
Then try to rename the cells:
```
> mono <- RenameCells(object = mono, new.names = mono_names)
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
> traceback()
11: stop("invalid 'row.names' length")
10: `.rowNamesDF<-`(x, value = value)
9: `row.names<-.data.frame`(`*tmp*`, value = value)
8: `row.names<-`(`*tmp*`, value = value)
7: `rownames<-`(x = `*tmp*`, value = new.names)
6: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
5: suppressWarnings(rownames(x = Misc(object = object, slot = "vst.out")$cell_attr) <- new.names)
4: RenameCells.Assay(object = object[[assay]], new.names = new.cell.names)
3: RenameCells(object = object[[assay]], new.names = new.cell.names)
2: RenameCells.Seurat(object = mono, new.names = mono_names)
1: RenameCells(object = mono, new.names = mono_names)
```
I'm not really sure why this is happening. I ran pretty much exactly the same thing for another Seurat object and it worked perfectly.

**Comment by Victor21v** [comment]
I can't rename my cells as well. I get the same error.

**Comment by timoast** [comment]
Which version of Seurat are you using?

**Comment by stephanieRedmond** [comment]
Hello, I'm getting the same error, either with RenameCells directly, or by trying to run FindTransferAnchors.

`transfer.anchors <- FindTransferAnchors(reference = object1, query = object2, normalization.method = "SCT", reference.assay = "SCT", query.assay = "SCT", dims = 1:30)`

and I was able to run IntegrateData on these objects successfully:
`object.integrated <- IntegrateData(anchorset = object.anchors, normalization.method = "SCT", verbose = T)`

I am using Seurat 3.1.5.9008

Here is my session info:

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] viridis_0.5.1     viridisLite_0.3.0 dplyr_0.8.4       ggplot2_3.2.1    
[5] Seurat_3.1.5.9008

loaded via a namespace (and not attached):
 [1] httr_1.4.1          tidyr_1.0.2         jsonlite_1.6.1      splines_3.6.3      
 [5] lsei_1.2-0          leiden_0.3.3        gtools_3.8.1        RcppParallel_4.4.4 
 [9] assertthat_0.2.1    ggrepel_0.8.1       globals_0.12.5      pillar_1.4.3       
[13] lattice_0.20-41     glue_1.3.1          reticulate_1.14     digest_0.6.25      
[17] RColorBrewer_1.1-2  colorspace_1.4-1    cowplot_1.0.0       htmltools_0.4.0    
[21] Matrix_1.2-18       plyr_1.8.5          pkgconfig_2.0.3     listenv_0.8.0      
[25] purrr_0.3.3         patchwork_1.0.1     scales_1.1.0        RANN_2.6.1         
[29] gdata_2.18.0        Rtsne_0.15          tibble_2.1.3        withr_2.1.2        
[33] ROCR_1.0-7          pbapply_1.4-2       lazyeval_0.2.2      survival_3.1-8     
[37] magrittr_1.5        crayon_1.3.4        future_1.16.0       nlme_3.1-147       
[41] MASS_7.3-51.6       gplots_3.0.3        ica_1.0-2           tools_3.6.3        
[45] fitdistrplus_1.0-14 data.table_1.12.8   lifecycle_0.1.0     stringr_1.4.0      
[49] plotly_4.9.2        munsell_0.5.0       cluster_2.1.0       irlba_2.3.3        
[53] compiler_3.6.3      rsvd_1.0.3          caTools_1.18.0      rlang_0.4.4        
[57] grid_3.6.3          ggridges_0.5.2      rstudioapi_0.11     RcppAnnoy_0.0.14   
[61] rappdirs_0.3.1      htmlwidgets_1.5.1   igraph_1.2.4.2      bitops_1.0-6       
[65] npsurv_0.4-0        gtable_0.3.0        codetools_0.2-16    reshape2_1.4.3     
[69] R6_2.4.1            gridExtra_2.3       zoo_1.8-7           knitr_1.28         
[73] uwot_0.1.5          future.apply_1.4.0  KernSmooth_2.23-17  ape_5.3            
[77] stringi_1.4.6       parallel_3.6.3      Rcpp_1.0.3          sctransform_0.2.1  
[81] vctrs_0.2.3         png_0.1-7           tidyselect_1.0.0    xfun_0.12          
[85] lmtest_0.9-37      
```

**Comment by satijalab** [comment]
We'll take a look at this, and may have seen something similar. To help us debug can you confirm if this happens if you only do standard log-normalization and not SCT? Thanks!

**Comment by camerongw** [comment]
I can't speak for other commenters but my issue is only in the RenameCells function. 
SessionInfo():
`
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/local/easybuild/software/OpenBLAS/0.2.19-GCC-6.2.0-LAPACK-3.7.0/lib/libopenblas_haswellp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Seurat_3.1.5

loaded via a namespace (and not attached):
 [1] httr_1.4.1          tidyr_1.1.0         jsonlite_1.6.1
 [4] viridisLite_0.3.0   splines_3.5.1       lsei_1.2-0
 [7] leiden_0.3.3        gtools_3.8.1        assertthat_0.2.1
[10] ggrepel_0.8.2       globals_0.12.5      pillar_1.4.4
[13] lattice_0.20-35     glue_1.4.1          reticulate_1.10
[16] digest_0.6.25       RColorBrewer_1.1-2  colorspace_1.3-2
[19] cowplot_0.9.3       htmltools_0.4.0     Matrix_1.2-14
[22] plyr_1.8.6          pkgconfig_2.0.2     tsne_0.1-3
[25] listenv_0.8.0       purrr_0.3.4         patchwork_1.0.0
[28] scales_1.1.1        RANN_2.6            gdata_2.18.0
[31] Rtsne_0.13          tibble_3.0.1        ggplot2_3.3.0
[34] ellipsis_0.3.1      ROCR_1.0-7          pbapply_1.3-4
[37] lazyeval_0.2.2      survival_2.42-6     magrittr_1.5
[40] crayon_1.3.4        future_1.17.0       nlme_3.1-137
[43] MASS_7.3-50         gplots_3.0.1        ica_1.0-2
[46] tools_3.5.1         fitdistrplus_1.0-11 data.table_1.12.8
[49] lifecycle_0.2.0     stringr_1.4.0       plotly_4.9.2.1
[52] munsell_0.5.0       cluster_2.0.7-1     irlba_2.3.2
[55] compiler_3.5.1      rsvd_1.0.3          caTools_1.17.1.1
[58] rlang_0.4.6         grid_3.5.1          ggridges_0.5.0
[61] RcppAnnoy_0.0.16    htmlwidgets_1.5.1   igraph_1.2.2
[64] bitops_1.0-6        npsurv_0.4-0        gtable_0.3.0
[67] codetools_0.2-15    reshape2_1.4.3      R6_2.4.1
[70] gridExtra_2.3       zoo_1.8-3           dplyr_0.8.5
[73] uwot_0.1.8          future.apply_1.5.0  KernSmooth_2.23-15
[76] ape_5.1             stringi_1.4.6       parallel_3.5.1
[79] Rcpp_1.0.4.6        vctrs_0.3.0         sctransform_0.2.1
[82] png_0.1-7           tidyselect_1.1.0    lmtest_0.9-36
`

**Comment by timoast** [comment]
This should be fixed on the develop branch (0ef1df468576075c2f4298240c190e5f888935e1)

**Comment by camerongw** [comment]
I've just installed Seurat_3.1.5.9009, should the issue be fixed in this version? I've been able to reproduce it by running the same code as I initially posted above.

**Comment by jstraubhr** [comment]
Same error when using FindTransferAnchors() with scRNAseq reference and scATACseq query. The error occurs with RenameCells(). Renaming query cells works but not for reference cells.

Function call:  FindTransferAnchors(reference=RNAobj, query=ATACobj, reference.assay='RNA', query.assay='RNA', reduction='cca')
This uses 'LogNormalize' by default.

The query RNA assay contains the gene activity matrix.

I am using 
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

**Comment by jstraubhr** [comment]
Continuing my earlier comment

The code loops through all reference assays: RNA, SCT, integrated. When it gets to SCT it does this

suppressWarnings(Misc(object, slot = "vst.set") <- lapply(X = Misc(object = object, slot = "vst.set"), FUN = function(x) {
    new.names.vst <- new.names[which(x = x$cells_step1 %in% Cells(x = object))]
    x$cells_step1 <- new.names.vst
    rownames(x = x$cell_attr) <- new.names.vst
    return(x)
}))

At line 4 (rownames(...) <- new.names.vst) it throws the error

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

new.names.vst is empty

**Comment by stephanieRedmond** [comment]
> We'll take a look at this, and may have seen something similar. To help us debug can you confirm if this happens if you only do standard log-normalization and not SCT? Thanks!

Hi. I haven't had server time to log-normalize my data to try that. But I have been having the same issue as described, despite using the develop branch of Seurat3. Thanks!

**Comment by timoast** [comment]
This is fixed in the current release. However, if you have a Seurat object containing an SCT assay that you previously subset before the commit I referenced above you will need to re-generate that subset object using the latest version of Seurat

**Comment by jstraubhr** [comment]
This still doesn't work and returns the same error. This issue should be kept open.

**Comment by timoast** [comment]
@jstraubhr please open a new issue with a reproducible example
