### ISSUE TITLE
Averageexpression return same value

### ISSUE THREAD

**Issue by Coolchong** [satijalab/seurat#3248]
Dear Seurat team,

After reading issue #2413 and #3130,
First I am still confuse whether I can use "data" slot from SCT assay to do the average expression, since one answer suggests it is reasonable, the other answer suggests it is not meaningful.

Second, for my dataset which has been SCTransformed but not integrated, the averageexpression return differently when I do averageexpression for all features or on one specific features and also it is different after subsetting, which I do not understand why. 
A:
avg<-AverageExpression(Macrophage,assay = "SCT",return.seurat = T)
FetchData(avg,vars = "Cdkn1a")
      Cdkn1a
0  2.4393372
1  0.8706338
2  1.0949074
3  0.6714853
4  2.1579540
5  0.9056568
6  2.4325485
7  1.7626455
8  2.1053662
9  2.0324125
10 1.4622457
11 1.2713477
12 1.9145818
13 2.6194257
14 1.9559294
15 2.0866382
16 1.9448085

B: avg<-AverageExpression(Macrophage,assays = "SCT",features = "Cdkn1a",return.seurat = T)
FetchData(avg,vars = "Cdkn1a")
    Cdkn1a
0  9.21044
1  9.21044
2  9.21044
3  9.21044
4  9.21044
5  9.21044
6  9.21044
7  9.21044
8  9.21044
9  9.21044
10 9.21044
11 9.21044
12 9.21044
13 9.21044
14 9.21044
15 9.21044
16 9.21044

Could you help me understand what causes this issue? 

Thanks a lot!

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting! This should now be resolved in the latest version of Seurat.

**Comment by Coolchong** [comment]
Thank you for looking into this question,
but I still have some issue using averageexpression function. The average expression works fine without subsetting:
levels(x)<-c("Macrophage_lysmwt","Macrophage_lysmp21","Monocyte_lysmwt","Monocyte_lysmp21" )

avg<-AverageExpression(x,assay = "RNA",features = c("Il1a","Il1b","Vegfa"),return.seurat =  T)
FetchData(avg,vars = c("Il1a","Il1b","Vegfa"),slot = "scale.data")
                                               Il1a       Il1b      Vegfa
Macrophage_lysmwt   0.5128832 -0.8978258  0.1544425
Macrophage_lysmp21  1.1419768  0.4970158  1.3454689
Monocyte_lysmwt    -1.0056982  1.1664691 -0.8931231
Monocyte_lysmp21   -0.6491618 -0.7656592 -0.6067882

However, after subsettings it returned to same value again
Idents(x)<-"rawcelltype"
levels(x)
[1] "Macrophage" "Monocyte" 
macs<-subset(x,idents = "Macrophage")
all.genes <- rownames(macs)
macs.scale <- ScaleData(macs, features = all.genes)
macs.scale$rawcelltype.genotype <- paste(macs.scale$rawcelltype, macs.scale$genotype, sep = "_")
Idents(macs.scale)<-"rawcelltype.genotype"
levels(macs.scale)<-c("Macrophage_lysmwt","Macrophage_lysmp21")
avg1<-AverageExpression(macs.scale,assay = "RNA",features = c("Il1a","Il1b","Vegfa"),return.seurat =  T)
FetchData(avg1,vars = c("Il1a","Il1b","Vegfa"),slot = "scale.data")
                                              Il1a       Il1b      Vegfa
Macrophage_lysmwt  -0.7071068 -0.7071068 -0.7071068
Macrophage_lysmp21  0.7071068  0.7071068  0.7071068


The data slot from both average look the same, only the scale.data slot somehow changed, I don't understand why:
FetchData(avg,vars = c("Il1a","Il1b","Vegfa"),slot = "data")
                                             Il1a     Il1b     Vegfa
Macrophage_lysmwt  0.9392068 3.787149 0.9940962
Macrophage_lysmp21 1.2468417 3.922814 1.4296236
Monocyte_lysmwt    0.1966008 3.987926 0.6110288
Monocyte_lysmp21   0.3709517 3.800003 0.7157340

FetchData(avg1,vars = c("Il1a","Il1b","Vegfa"),slot = "data")
                                               Il1a     Il1b     Vegfa
Macrophage_lysmwt  0.9392068 3.787149 0.9940962
Macrophage_lysmp21 1.2468417 3.922814 1.4296236
