### ISSUE TITLE
Updated Cell Selector with shiny app

### ISSUE THREAD

**Issue by sgolomb** [satijalab/seurat#3412]
I am trying to use the cell selector tool to gate cells that were stained with ADT (or CITE antibodies) from a CITEseq experiment. With the updated version using the shiny app, it seems that cell selector or shiny is having trouble recognizing cells selected with indicated CITE antibodies in the plot. At first I thought this was an issue recognizing dashes and I removed dashes and replaced with dots, however the issue is still occurring. After changing the ADT column names to remove dashes, I could not create a feature scatter plot - so my issue may be related to an error in attempting to change the column names in the ADT assay data. 

The cell selector works fine when I create a plot with gene names, so I feel that the issue is surrounding the CITE naming system. Any suggestions on how to ensure the CITE names can be recognized with the updated cell selector tool?

Here is my code to create a biaxial plot with CITE antibodies (this is the version with original ADT naming):

#create biaxial plot for gating on object of interest
test_plotCD45xCD11b <-FeatureScatter(test_pbmc.singlet.backup, feature1 = "cite_CITE-CD45", feature2 = "cite_CITE-CD11b")
#gate on cells of interest and assign IDs
test_pbmc.singlet.backup <- CellSelector(plot = test_plotCD45xCD11b, object = test_pbmc.singlet.backup, ident = "CD45High")

The biaxial and interactive tool starts to work but while I begin dragging the cursor over cells of interest, the plot disappears and the following error comes up:

Listening on http://127.0.0.1:4306
Warning: Error in brushedPoints: brushedPoints: `xvar` ('cite_CITE.CD45')  not in names of input
  76: stop
  75: brushedPoints
  74: observeEventHandler
   3: shiny::runApp
   2: runGadget
   1: CellSelector

I do not get any error if I use gene names. 
Example:
genetest_plotCD45xCD11b <-FeatureScatter(test_pbmc.singlet.backup, feature1 = "Ptprc", feature2 = "Itgam")
test_pbmc.singlet.backup <- CellSelector(plot = genetest_plotCD45xCD11b, object = test_pbmc.singlet.backup, ident = "CD45High")

Main questions: Where/how (object, assay, table..?) is the ideal place to change the ADT column names? Is there a particular naming system that would be ideal? Has anyone else experienced this issue?

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by sgolomb** [comment]
I tried installing the development version by the linked instructions. I updated R and R Studio to the latest versions and am still having a problem with selecting cells via CITE antibodies. I do not have an issue with gene names. Is this related to the naming system I am using the the CITE antibodies in my plot?
I appreciate your help!

> plotCD335xCD117 <-FeatureScatter(test_cells, feature1 = "cite_CITE-CD335", feature2 = "cite_CITE-CD117-c-kit")
> test_cells <- CellSelector(plot = plotCD335xCD117, object = test_cells, ident = "CD335+")
Loading required package: shiny

Listening on http://127.0.0.1:5069
Warning: Error in brushedPoints: brushedPoints: `xvar` ('cite_CITE.CD335')  not in names of input
  76: stop
  75: brushedPoints
  74: observeEventHandler
   3: shiny::runApp
   2: runGadget
   1: CellSelector

Warning message:
Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
This warning is displayed once per session.

**Comment by mojaveazure** [comment]
I am unable to replicate your issue; can you provide a dataset, subset of a dataset, or dataset in [SeuratData](https://github.com/satijalab/seurat-data) that reproduces this error? If you don't want to share your data publicly, you can email me at phoffman@nygenome.org

**Comment by sgolomb** [comment]
Hi Paul,

We actually were able to get the cell selector working! I think it took a few iterations of updating everything and restarting R and R Studio. Will let you know if there are future issues.

Thank you!

Sam
