### ISSUE TITLE
Subset: Error in `[[.DimReduc`(x, cells, , drop = FALSE): None of the requested embeddings are present.

### ISSUE THREAD

**Issue by shhxiao19** [satijalab/seurat#3574]
Hi,

I'm trying to subset a Seurat object that was created from a Liger object (using "ligerToSeurat"). The subset() function gave the following error:
Error in `[[.DimReduc`(x, cells, , drop = FALSE): None of the requested embeddings are present.

I used Seurat 3.2.2 in R 4.0.2. Could you please advise what I should do? Thank you.

**Comment by samuel-marsh** [comment]
Hi,

Having same error, appears to be change in Seurat 3.2+.  As short term solution you can downgrade to Seurat 3.15 convert to Seurat and subset and then reinstall 3.22.  Has worked for me when I ran into this issue yesterday as well.

Best,
Sam

**Comment by shhxiao19** [comment]
Thank you for the suggestion, @samuel-marsh. It worked. The subset() function also worked in Seurat 3.2.0.

Best regards.

**Comment by mojaveazure** [comment]
Can you provide a reproducible example using one of the datasets provided by [SeuratData](https://github.com/satijalab/seurat-data)?

**Comment by shhxiao19** [comment]
Hi @mojaveazure , 

Thank you for following up. I used the "ifnb" dataset from the SeuratData and reproduced the error by running the following code in Seurat 3.2.2. The same code worked in Seurat 3.2.0 without any errors.

InstallData("ifnb")
data("ifnb")

ifnb.list <- SplitObject(ifnb, split.by = "stim")
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

ifnb_lo <- seuratToLiger(ifnb.list, names = "use-meta", meta.var = "stim", use.idents = F, use.tsne = F)
ifnb_lo <- scaleNotCenter(ifnb_lo)
ifnb_lo <- optimizeALS(ifnb_lo, k = 20, nrep = 1)
ifnb_lo <- quantile_norm(ifnb_lo)
ifnb_lo <- louvainCluster(ifnb_lo)
ifnb_lo <- runUMAP(ifnb_lo, distance = 'cosine')

so_fromLiger <- ligerToSeurat(ifnb_lo)
so_fromLiger[['tsne']]@global <- TRUE
so_fromLiger[['inmf']]@global <- TRUE
so_ctrl <- subset(so_fromLiger, subset= orig.ident == "CTRL")

Here is the error in Seurat 3.2.2
<img width="468" alt="subset_error_322" src="https://user-images.githubusercontent.com/46549080/95648393-87340f80-0a8b-11eb-86d1-6a73af6ec6eb.png">

Do you have any suggestions on how to solve the problem in Seurat 3.2.2? Thank you.

Best regards.

**Comment by mojaveazure** [comment]
This issue occurs because the `inmf` dimensional reduction does not put column names in the cell embeddings matrix. This can be fixed by rebuilding the `inmf` object and letting `CreateDimReducObject` take care of the object creation and validation

```R
so_fromLiger[['inmf']] <- CreateDimReducObject(
  embeddings = Embeddings(so_fromLiger[['inmf']]),
  loadings = Loadings(so_fromLiger[['inmf']], projected = FALSE),
  projected = Loadings(so_fromLiger[['inmf']], projected = TRUE),
  assay = DefaultAssay(so_fromLiger[['inmf']]),
  stdev = Stdev(so_fromLiger[['inmf']]),
  key = Key(so_fromLiger[['inmf']]),
  global = TRUE,
  misc = Misc(object = so_fromLiger[['inmf']])
)
```

Unfortunately, we don't have a timeline for a fix.

As an aside, if you use the [Seurat/Liger wrapper](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/liger.html) functions provided by [SeuratWrappers](https://github.com/satijalab/seurat-wrappers/), this issue is non existent as the wrapper functions create the `DimReduc` object properly. The caveat to this approach is that you don't get LIGER's clustering or UMAP implementations, but instead you have to use Seurat's.

**Comment by shhxiao19** [comment]
Hi @mojaveazure,

Thank you for solving the problem!

Best regards.

**Comment by mojaveazure** [comment]
I've filed a [pull request](https://github.com/MacoskoLab/liger/pull/190) for LIGER that will properly create and add dimensional reduction information to the `Seurat` object in `ligerToSeurat`; once accepted, then `Seurat` objects created by `ligerToSeurat` will work with Seurat code.

**Comment by shhxiao19** [comment]
That's Great. Thank you.

**Comment by samuel-marsh** [comment]
Hi @shhxiao19,

Liger team just pushed @mojaveazure's PR to the master branch.  Redownloading the master branch of LIGER will include updated seuratToLiger function and should solve the issue.

Best,
Sam

**Comment by shhxiao19** [comment]
Thank you for the update, @samuel-marsh.

Best regards.

**Comment by grimwoo** [comment]
@mojaveazure thanks for developing `Seurat::CreateDimReducObject()` function. I still does not understand how to use this function to process the object that cannot  be subset (Error in [[.DimReduc(x, cells, , drop = FALSE): None of the requested embeddings are present.). Because I encounteresd this issue on Seurat v4.0.1 and v4.0.6.

**Comment by grimwoo** [comment]
I found that in the new Seurat package environment, the error occurs because it was create by the previous Seurat package. We just have to update the Seurat object by `Seurat.object.NEW <- CreateSeuratObject(counts = Seurat.object@assays$RNA@counts, meta.data = Seurat.object@meta.data)`
