### ISSUE TITLE
crop = FALSE  causes an error in function SpatialFeaturePlot

### ISSUE THREAD

**Issue by EternalEnvy10** [satijalab/seurat#4003]
Hi, I have I'm currently having the same issue as reported in issue #2700, spot will pan to the wrong place as a whole, as mentioned above. I have upgraded ggplot2 to the latest version 3.3.3.
Thanks!!

**Comment by k3yavi** [comment]
Hey @EternalEnvy10 ,

Did you also pulled the latest spatial branch and reinstalled Seurat ? Can you also share the session_info for your environment ?

**Comment by EternalEnvy10** [comment]
Hi @k3yavi,
Thanks for your reply, do you mean to let me reinstall Seurat in RStudio?
How do I share session_info to you?

Thanks!!

**Comment by kaikaixinxi** [comment]
i also have the same issue,  i used the Seurat 4.0.0 and ggplot2 3.3.3
![image](https://user-images.githubusercontent.com/34878405/113532051-051d4180-95fd-11eb-83ae-aa928d2a65f0.png)

**Comment by k3yavi** [comment]
Hi @kaikaixinxi ,

Is it possible to share the data with us ? Unfortunately we can't replicate the issue on the open 10x datasets. If it's possible to share the data, can you please share it at `seuratpackage@gmail.com` ?

**Comment by andrewwbutler** [comment]
I believe this issue should now be resolved in the develop branch. Could you try installing that (instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)) and see if that resolves the issue?

**Comment by EternalEnvy10** [comment]
Hi @andrewwbutler ,
Now I'm using the latest version(4.0.1), but the problem remains.T_T

**Comment by andrewwbutler** [comment]
Hi @EternalEnvy10 ,

The latest develop version is `4.0.1.9013`. Please be sure you have installed that version.

**Comment by EternalEnvy10** [comment]
Hi @andrewwbutler ,
I updated Seurat to version 4.0.2 and the problem was solved for good!
 :)Thank you very much!!!! This problem has been bothering us for a long time.
