### ISSUE TITLE
Error: Unable to find highly variable feature information for method 'sct'

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4018]
Hello there, 

After SCTransform(), I did VariableFeatures() of my Seurat objects. That allows me to pull out the 3000 variable genes. 

However, when I ran VariableFeaturePlot() of the same object, it has this error. 

Any idea? 

Thank you for your help!

<img width="856" alt="Screen Shot 2021-02-03 at 3 35 28 PM" src="https://user-images.githubusercontent.com/62179082/106769987-72c8e380-6635-11eb-9ae8-917db631eacf.png">

**Comment by torkencz** [comment]
Hmm. Could you post the code that you ran?

**Comment by yuhanH** [comment]
Thanks for reporting this bug. We will fix it soon. 
If you want to run `VariableFeaturePlot` in your SCTAssay, you can add some related information to the SCT assay meta.features
```
DefaultAssay(pbmc_small)<-"RNA"
pbmc_small <- SCTransform(pbmc_small, variable.features.n = 10)
 
var <- c('gmean', 'variance', 'residual_variance')
pbmc_small[["SCT"]]@meta.features <- SCTResults(pbmc_small[["SCT"]], slot = "feature.attributes")[, var]
pbmc_small[["SCT"]]@meta.features$variable <- FALSE
pbmc_small[["SCT"]]@meta.features[VariableFeatures(pbmc_small[["SCT"]] ), "variable"] <- TRUE
colnames(pbmc_small[["SCT"]]@meta.features) <- paste0("sct.", colnames(pbmc_small[["SCT"]]@meta.features) )
VariableFeaturePlot(pbmc_small, selection.method = "sct", assay = "SCT")

```

**Comment by denvercal1234GitHub** [comment]
Thank you @yuhanH! 

Also, would you mind helping me to understand when it makes sense to use data from the RNA Assay versus SCT Assay for plotting:
+ Variable features?
+ Cluster markers?
+ Expression level of a gene?

I know that RNA Assay contains raw count data whereas the SCT Assay contains [counts = (corrected) counts; data = log1p(counts); scale.data = pearson residuals]. So for Heatmap, for example, plotting scale.data from SCT Assay would avoid too highly-expressed genes to dominate, but I am unsure about the other cases. 

Thank you so much for your help!

**Comment by bounlu** [comment]
I get exactly the same error.

**Comment by yuhanH** [comment]
It is fixed in our latest develop branch.

**Comment by bounlu** [comment]
I installed the latest develop version just now but I can confirm that I still get the same error.

```
library(devtools)
install_github(repo = "satijalab/seurat", ref = "develop")
library(Seurat)

top = head(VariableFeatures(s_df), top_n_features)
plot = LabelPoints(plot = VariableFeaturePlot(s_df), points = top, repel = TRUE, xnudge = 0, ynudge = 0)
Error: Unable to find highly variable feature information for method 'sct'
```

**Comment by JTpath** [comment]
Ditto

**Comment by yuhanH** [comment]
You are right... sorry about the confusion... 
I made sure that the bug is fixed in the latest develop branch now. You can find the correspond commit here. 
https://github.com/satijalab/seurat/commits/develop

one example:
```
DefaultAssay(pbmc_small)<-"RNA"
pbmc_small <- SCTransform(pbmc_small, variable.features.n = 10)
VariableFeaturePlot(pbmc_small, selection.method = "sct", assay = "SCT")
```

**Comment by bounlu** [comment]
yep, now it works! 👌🏼 thx!

**Comment by denvercal1234GitHub** [comment]
@yuhanH - I am sorry but I think the error "No requested features found in the scale.data slot for the SCT assay" still happens for DoHeatmap() in the SCTransform() workflow.

**Comment by yuhanH** [comment]
HI, @denvercal1234GitHub 
Thanks. Also if the target genes are not in the scale.data slot, you can use `GetResiduals` to obtain residuals for your target genes.

**Comment by duocang** [comment]
Hi.

After installation of the latest dev version, I still have the error.
![image](https://user-images.githubusercontent.com/14146871/110960541-261caa80-834f-11eb-8077-d06130db0761.png)
