### ISSUE TITLE
Error in ScaleData

### ISSUE THREAD

**Issue by vthaker** [satijalab/seurat#618]
Hi there,
We are using Seurat to analyze a dataset of 13,000 cells from mouse brain prepared in 9 batches. 
We have ~2658 variable genes in the @var.genes. Could you please advise on overcoming the error we encounter. Thanks
```R
objectname <- ScaleData(object = name, vars.to.regress = c("percent.mito", "orig.ident", "nUMI"), genes.use = name@var.genes)

[1] "Regressing out percent.mito" "Regressing out orig.ident"   "Regressing out nUMI"        
  |===================================================================================| 100%
Time Elapsed:  4.00979118347168 mins
[1] "Scaling data matrix"
  |                                                                                   |   0%Error in scaled.data[genes.use[my.inds], ] <- data.scale : 
  number of items to replace is not a multiple of replacement length

sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2 dplyr_0.7.4    Seurat_2.3.0   Matrix_1.2-14  cowplot_0.9.2  ggplot2_2.2.1 

loaded via a namespace (and not attached):
  [1] diffusionMap_1.1-0   Rtsne_0.13           VGAM_1.0-5           colorspace_1.3-2    
  [5] ggridges_0.5.0       class_7.3-14         modeltools_0.2-21    mclust_5.4          
  [9] htmlTable_1.11.2     base64enc_0.1-3      proxy_0.4-22         rstudioapi_0.7      
 [13] DRR_0.0.3            flexmix_2.3-14       prodlim_2018.04.18   mvtnorm_1.0-7       
 [17] lubridate_1.7.4      ranger_0.9.0         codetools_0.2-15     splines_3.4.3       
 [21] R.methodsS3_1.7.1    mnormt_1.5-5         robustbase_0.92-8    knitr_1.20          
 [25] tclust_1.3-1         RcppRoll_0.2.2       Formula_1.2-2        caret_6.0-79        
 [29] ica_1.0-1            broom_0.4.4          ddalpha_1.3.2        cluster_2.0.7-1     
 [33] kernlab_0.9-25       png_0.1-7            R.oo_1.22.0          sfsmisc_1.1-2       
 [37] compiler_3.4.3       backports_1.1.2      assertthat_0.2.0     lazyeval_0.2.1      
 [41] lars_1.2             acepack_1.4.1        htmltools_0.3.6      tools_3.4.3         
 [45] igraph_1.2.1         gtable_0.2.0         glue_1.2.0           RANN_2.5.1          
 [49] reshape2_1.4.3       Rcpp_0.12.17         trimcluster_0.1-2    gdata_2.18.0        
 [53] ape_5.1              nlme_3.1-137         iterators_1.0.9      fpc_2.1-11          
 [57] lmtest_0.9-36        psych_1.8.3.3        timeDate_3043.102    gower_0.1.2         
 [61] stringr_1.3.0        irlba_2.3.2          gtools_3.5.0         DEoptimR_1.0-8      
 [65] zoo_1.8-1            MASS_7.3-50          scales_0.5.0         ipred_0.9-6         
 [69] doSNOW_1.0.16        parallel_3.4.3       RColorBrewer_1.1-2   yaml_2.1.18         
 [73] pbapply_1.3-4        gridExtra_2.3        segmented_0.5-3.0    rpart_4.1-13        
 [77] latticeExtra_0.6-28  stringi_1.1.7        foreach_1.4.4        checkmate_1.8.5     
 [81] caTools_1.17.1       lava_1.6.1           geometry_0.3-6       dtw_1.18-1          
 [85] SDMTools_1.1-221     rlang_0.2.1          pkgconfig_2.0.1      prabclus_2.2-6      
 [89] bitops_1.0-6         lattice_0.20-35      ROCR_1.0-7           purrr_0.2.4         
 [93] bindr_0.1.1          recipes_0.1.2        htmlwidgets_1.2      tidyselect_0.2.4    
 [97] CVST_0.2-1           plyr_1.8.4           magrittr_1.5         R6_2.2.2            
[101] snow_0.4-2           gplots_3.0.1         Hmisc_4.1-1          dimRed_0.1.0        
[105] sn_1.5-2             withr_2.1.2          pillar_1.2.2         foreign_0.8-70      
[109] mixtools_1.1.0       fitdistrplus_1.0-9   survival_2.42-3      scatterplot3d_0.3-41
[113] abind_1.4-5          nnet_7.3-12          tsne_0.1-3           tibble_1.4.2        
[117] KernSmooth_2.23-15   grid_3.4.3           data.table_1.11.4    FNN_1.1             
[121] ModelMetrics_1.1.0   metap_0.9            digest_0.6.15        diptest_0.75-7      
[125] numDeriv_2016.8-1    tidyr_0.8.0          R.utils_2.6.0        stats4_3.4.3        
[129] munsell_0.4.3        magic_1.5-8      
```

**Comment by evolvedmicrobe** [comment]
If you rerun the command with `vars.to.regress = NULL` does the error still appear?

**Comment by vthaker** [comment]
The command runs in that condition. Does that tell you why I got the error? 
I want to correct for `"percent.mito", "orig.ident"`, as my batches are dissimilar.

**Comment by vthaker** [comment]
@evolvedmicrobe trying the code above. 
Is `RegressOutResid` a valid Seurat function for v2.3.0?
Here is what I find: `RegressOut` now part of `ScaleData`.

**Comment by evolvedmicrobe** [comment]
Whoops, try ‘Seurat:::RegressOutResid’ as the function name

**Comment by vthaker** [comment]
` data.use.2 <- Seurat:::RegressOutResid(
+   object = name,
+   vars.to.regress = vars.to.regress,
+   genes.regress = genes.use,
+   use.umi = FALSE,
+   model.use = 'linear',
+   display.progress = TRUE,
+   do.par = FALSE,
+   num.cores = 1
+ )
Regressing out: percent.mito, orig.ident, nUMI
  |=========================================================================================| 100%Error in { : 
  task 1 failed - "'qr' and 'y' must have the same number of rows"
> `

**Comment by evolvedmicrobe** [comment]
Have you changed versions or data at all since the initial report?  I noticed the first message was ` "Regressing out percent.mito" "Regressing out orig.ident" "Regressing out nUMI"` while this message has them all combined as expected (`Regressing out: percent.mito, orig.ident, nUMI`).  It's also a bit weird that the error was thrown this time.

That error may explain the problem though.  Is it possible you have missing data somewhere in your matrix?  You can check if so using the code below:

    vars.to.regress = c("percent.mito", "orig.ident", "nUMI")
    latent.data <- FetchData(object = name, vars.all = vars.to.regress)
    genes.regress <- intersect(x = genes.use, y = rownames(x = name@data))
    data.use.3 <- name@data[genes.regress, , drop = FALSE];
    print(any(is.na(data.use.3)) | any(is.infinite(data.use.3)))
    print(any(is.na(latent.data)) | any(is.infinite(latent.data)))

If for some genes you have an "NA" value for some cells data, then when you standardize by regressing out the residuals you'll be returning different sized residuals each time, and this could create a data size mismatch, leading to the error.

**Comment by vthaker** [comment]
@evolvedmicrobe 
Thanks for the response. Discovered the problem based on your response. I do have a lot of "NA" in `orig.ident` 
This is likely an issue with one of the upstream functions. 

Here is my workflow because I wanted all cells to have similar id like such `1B_CCCCC......, 9B_CTCCG..` and so on.

Step 1: merge 2 Seurat objects: 
`MergeSeurat(object1 = name1, object2 = name2, add.cell.id1 = "1B", add.cell.id2 = "2B")`
In this step, I expected the `orig.ident` to be `1B`, and `2B` as factor. The `orig.ident` is actually being stored as a `chr` and not `Factor` with the value entered for `project =name_B1`
Step 2: `AddSamples(object = seurat1, new.data = name3.data, add.cell.id = "3B")`

Now, in Step 2, `orig.ident` changes to factor, but I lose the `orig.ident` for `1B` and `2B`, generating the NAs and the issue. 

This did not happen when I worked with another dataset a few months ago, before the `AddSamples
` function was introduced. 
Hope that makes sense. I modified the workflow to account for the bug there, and now works fine.

**Comment by evolvedmicrobe** [comment]
Great! Glad it was resolved, I also opened a pull request to help make it easier for someone to identify this issue later on.

Am not sure about the expected behavior of `AddSamples` vs. `MergeSeurat`, but indeed see what you mean about the factor conversion creating `<NA>` values.

**Comment by Lucyyang1991** [comment]
I found that when we use Merge function, the cells which have the same cell barcodes will create the NAs. But I still do not know how to solve this problems
