### ISSUE TITLE
Error in .local(x, na.rm, dims, ...) : object 'CRsparse_colSums' not found

### ISSUE THREAD

**Issue by alasaa** [satijalab/seurat#8094]
...could anyone please help me...(T~T)...I can't live without a Seurat
1.  I use R4.3.2, Seurat v5, and I got the bug: Error in .local(x, na.rm, dims, ...) : object 'CRsparse_colSums' not found
2.  the same code and same data and same verson of R can work on other person's PC.
3.  I even have tried to reinstalling software of R, Rstudio, Rtools and Python, reinstall all packages, restart the computer...But I met the same error when I RunUMAP.
4. The following is detailed error information:

> obj <- RunUMAP(obj,dims = 1:40,reduction = "pca",reduction.name = "umap.unintegrated")
Warning: The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
This message will be shown once per session
01:53:51 UMAP embedding parameters a = 0.9922 b = 1.112
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by 'spam'
01:53:51 Read 132148 rows and found 40 numeric columns
01:53:51 Using Annoy for neighbor search, n_neighbors = 30
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by 'spam'
01:53:51 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
01:54:14 Writing NN index file to temp file C:\Users\alasa\AppData\Local\Temp\RtmpeUNPAH\file257c51a12d08
01:54:14 Searching Annoy index using 1 thread, search_k = 3000
01:55:06 Annoy recall = 100%
01:55:06 Commencing smooth kNN distance calibration using 1 thread with target n_neighbors = 30
01:55:17 Initializing from normalized Laplacian + noise (using RSpectra)
Error in .local(x, na.rm, dims, ...) : object 'CRsparse_colSums' not found

**Comment by Jyng321** [comment]
Hi alasaa,
I had the same problem after I installed the rlang package. 
I could solve the problem with these steps. I hope it could be helpful for you in the time to wait a response from an expert.
1. Restart R (in RStudio, click Session then Restart R).
2. In the R console, run update.packages(). 
3. If you get the message shown in your second screen shot ("One or more of the packages …"), click "No", since you have already re-started R.
Best.

**Comment by weicoo** [comment]
I also meet the same problem. I have try restart it, but i doesn't work. Here is sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8 
[2] LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8
[4] LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38_1.4.5 BSgenome_1.70.1                  
 [3] rtracklayer_1.62.0                BiocIO_1.12.0                    
 [5] Biostrings_2.70.1                 XVector_0.42.0                   
 [7] ggplot2_3.4.4                     Matrix_1.6-3                     
 [9] SummarizedExperiment_1.32.0       Biobase_2.62.0                   
[11] GenomicRanges_1.54.1              GenomeInfoDb_1.38.1              
[13] IRanges_2.36.0                    S4Vectors_0.40.2                 
[15] BiocGenerics_0.48.1               MatrixGenerics_1.14.0            
[17] matrixStats_1.1.0                 motifmatchr_1.24.0               
[19] chromVAR_1.24.0                   BiocParallel_1.36.0              

loaded via a namespace (and not attached):
 [1] DBI_1.1.3                   bitops_1.0-7               
 [3] rlang_1.1.2                 magrittr_2.0.3             
 [5] compiler_4.3.2              RSQLite_2.3.3              
 [7] png_0.1-8                   vctrs_0.6.4                
 [9] reshape2_1.4.4              stringr_1.5.1              
[11] pkgconfig_2.0.3             crayon_1.5.2               
[13] fastmap_1.1.1               ellipsis_0.3.2             
[15] caTools_1.18.2              utf8_1.2.4                 
[17] Rsamtools_2.18.0            promises_1.2.1             
[19] tzdb_0.4.0                  pracma_2.4.4               
[21] DirichletMultinomial_1.44.0 purrr_1.0.2                
[23] bit_4.0.5                   zlibbioc_1.48.0            
[25] cachem_1.0.8                CNEr_1.38.0                
[27] jsonlite_1.8.7              blob_1.2.4                 
[29] later_1.3.1                 DelayedArray_0.28.0        
[31] parallel_4.3.2              R6_2.5.1                   
[33] stringi_1.8.2               Rcpp_1.0.11                
[35] R.utils_2.12.3              readr_2.1.4                
[37] httpuv_1.6.12               tidyselect_1.2.0           
[39] abind_1.4-5                 yaml_2.3.7                 
[41] codetools_0.2-19            miniUI_0.1.1.1             
[43] lattice_0.22-5              tibble_3.2.1               
[45] plyr_1.8.9                  withr_2.5.2                
[47] shiny_1.8.0                 KEGGREST_1.42.0            
[49] BiocManager_1.30.22         pillar_1.9.0               
[51] DT_0.30                     plotly_4.10.3              
[53] generics_0.1.3              vroom_1.6.4                
[55] RCurl_1.98-1.13             hms_1.1.3                  
[57] munsell_0.5.0               scales_1.2.1               
[59] gtools_3.9.5                xtable_1.8-4               
[61] glue_1.6.2                  lazyeval_0.2.2             
[63] seqLogo_1.68.0              tools_4.3.2                
[65] TFMPvalue_0.0.9             data.table_1.14.8          
[67] annotate_1.80.0             GenomicAlignments_1.38.0   
[69] XML_3.99-0.15               TFBSTools_1.40.0           
[71] poweRlaw_0.70.6             grid_4.3.2                 
[73] tidyr_1.3.0                 AnnotationDbi_1.64.1       
[75] colorspace_2.1-0            GenomeInfoDbData_1.2.11    
[77] restfulr_0.0.15             cli_3.6.1                  
[79] fansi_1.0.5                 viridisLite_0.4.2          
[81] S4Arrays_1.2.0              dplyr_1.1.4                
[83] gtable_0.3.4                R.methodsS3_1.8.2          
[85] digest_0.6.33               SparseArray_1.2.2          
[87] rjson_0.2.21                htmlwidgets_1.6.3          
[89] R.oo_1.25.0                 memoise_2.0.1              
[91] htmltools_0.5.7             lifecycle_1.0.4            
[93] httr_1.4.7                  GO.db_3.18.0               
[95] mime_0.12                   bit64_4.0.5

**Comment by 1061047021lql-AI** [comment]
I also meet the same problem,When I run "Integrative analysis in Seurat v5",
But when I don't load two packages, SeuratWrappers and Azimuth, it will work successfully.
this is very weird

**Comment by 1061047021lql-AI** [comment]
> 



> I also meet the same problem,When I run "Integrative analysis in Seurat v5", But when I don't load two packages, SeuratWrappers and Azimuth, it will work successfully. this is very weird



> I also meet the same problem,When I run "Integrative analysis in Seurat v5", But when I don't load two packages, SeuratWrappers and Azimuth, it will work successfully. this is very weird

By the way, my version is 4.3.2 and loading the SeuratWrappers() package also works. As long as I don't load the Azimuth package,RunUMAP() runs successfully

**Comment by 1061047021lql-AI** [comment]
> I also meet the same problem,When I run "Integrative analysis in Seurat v5", But when I don't load two packages, SeuratWrappers and Azimuth, it will work successfully. this is very weird

By the way, my version is 4.3.2 and loading the SeuratWrappers() package also works. As long as I don't load the Azimuth package,RunUMAP() runs successfully

**Comment by Gesmira** [comment]
Hi all, 
This does seem to be a specific issue related to conflicts in `colSums` with TFBSTools that is now automatically loaded with Azimuth. 
```
> head(colSums(obj[["RNA"]]$counts))
# works fine 
> head(TFBSTools::colSums(obj[["RNA"]]$counts))
Error in .local(x, na.rm, dims, ...) : 
  object 'CRsparse_colSums' not found
  ```
Looking into it, but in the meantime not loading Azimuth should fix the issue. Will update here when we have a fix.

**Comment by alasaa** [comment]
> Thank you @Jyng321! @alasaa, let us know if this works for you. Since this issue is not easily reproducible, please include your `sessionInfo()` as well if you continue to have this problem.

I still have this error.....
I tried to save the object, restart RStudio, reload the object, and only  library(Seurat).....but still got: Error in .local(x, na.rm, dims, ...) : object 'CRsparse_colSums' not found

the follow is my sessionInfo()
> lapply(c('Matrix','Seurat','seuratobject',"Azimuth"), FUN = function(x){packageVersion(x)})
[[1]]
[1] '1.6.3'

[[2]]
[1] '5.0.1'

[[3]]
[1] '5.0.1'

[[4]]
[1] '0.5.0'

> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_5.0.1       SeuratObject_5.0.1 sp_2.1-1           shinyBS_0.61.1    

loaded via a namespace (and not attached):
  [1] fs_1.6.3                          ProtGenerics_1.34.0              
  [3] matrixStats_1.1.0                 spatstat.sparse_3.0-3            
  [5] bitops_1.0-7                      DirichletMultinomial_1.44.0      
  [7] TFBSTools_1.40.0                  httr_1.4.7                       
  [9] RColorBrewer_1.1-3                tools_4.3.1                      
 [11] sctransform_0.4.1                 utf8_1.2.4                       
 [13] R6_2.5.1                          DT_0.30                          
 [15] lazyeval_0.2.2                    uwot_0.1.16                      
 [17] rhdf5filters_1.14.1               withr_2.5.2                      
 [19] prettyunits_1.2.0                 gridExtra_2.3                    
 [21] progressr_0.14.0                  cli_3.6.1                        
 [23] Biobase_2.62.0                    spatstat.explore_3.2-5           
 [25] fastDummies_1.7.3                 EnsDb.Hsapiens.v86_2.99.0        
 [27] shinyjs_2.1.0                     spatstat.data_3.0-3              
 [29] readr_2.1.4                       ggridges_0.5.4                   
 [31] pbapply_1.7-2                     Rsamtools_2.18.0                 
 [33] R.utils_2.12.3                    parallelly_1.36.0                
 [35] BSgenome_1.70.1                   rstudioapi_0.15.0                
 [37] RSQLite_2.3.3                     generics_0.1.3                   
 [39] BiocIO_1.12.0                     gtools_3.9.5                     
 [41] ica_1.0-3                         spatstat.random_3.2-1            
 [43] googlesheets4_1.1.1               dplyr_1.1.4                      
 [45] GO.db_3.17.0                      Matrix_1.6-3                     
 [47] fansi_1.0.5                       S4Vectors_0.40.1                 
 [49] abind_1.4-5                       R.methodsS3_1.8.2                
 [51] lifecycle_1.0.4                   yaml_2.3.7                       
 [53] SummarizedExperiment_1.32.0       rhdf5_2.46.0                     
 [55] SparseArray_1.2.2                 BiocFileCache_2.10.1             
 [57] Rtsne_0.16                        grid_4.3.1                       
 [59] blob_1.2.4                        promises_1.2.1                   
 [61] shinydashboard_0.7.2              crayon_1.5.2                     
 [63] miniUI_0.1.1.1                    lattice_0.22-5                   
 [65] cowplot_1.1.1                     GenomicFeatures_1.54.1           
 [67] annotate_1.80.0                   KEGGREST_1.42.0                  
 [69] knitr_1.45                        pillar_1.9.0                     
 [71] GenomicRanges_1.54.1              rjson_0.2.21                     
 [73] future.apply_1.11.0               codetools_0.2-19                 
 [75] fastmatch_1.1-4                   leiden_0.4.3.1                   
 [77] glue_1.6.2                        data.table_1.14.8                
 [79] remotes_2.4.2.1                   vctrs_0.6.4                      
 [81] png_0.1-8                         spam_2.10-0                      
 [83] cellranger_1.1.0                  gtable_0.3.4                     
 [85] poweRlaw_0.70.6                   cachem_1.0.8                     
 [87] xfun_0.41                         Signac_1.12.0                    
 [89] S4Arrays_1.2.0                    mime_0.12                        
 [91] pracma_2.4.4                      survival_3.5-7                   
 [93] gargle_1.5.2                      RcppRoll_0.3.0                   
 [95] ellipsis_0.3.2                    fitdistrplus_1.1-11              
 [97] ROCR_1.0-11                       nlme_3.1-163                     
 [99] bit64_4.0.5                       progress_1.2.2                   
[101] filelock_1.0.2                    RcppAnnoy_0.0.21                 
[103] GenomeInfoDb_1.38.1               irlba_2.3.5.1                    
[105] KernSmooth_2.23-22                SeuratDisk_0.0.0.9021            
[107] colorspace_2.1-0                  seqLogo_1.68.0                   
[109] BiocGenerics_0.48.1               DBI_1.1.3                        
[111] tidyselect_1.2.0                  bit_4.0.5                        
[113] compiler_4.3.1                    curl_5.1.0                       
[115] hdf5r_1.3.8                       xml2_1.3.5                       
[117] DelayedArray_0.28.0               plotly_4.10.3                    
[119] rtracklayer_1.62.0                scales_1.2.1                     
[121] caTools_1.18.2                    lmtest_0.9-40                    
[123] rappdirs_0.3.3                    stringr_1.5.1                    
[125] digest_0.6.33                     goftest_1.2-3                    
[127] presto_1.0.0                      spatstat.utils_3.0-4             
[129] XVector_0.42.0                    htmltools_0.5.7                  
[131] pkgconfig_2.0.3                   MatrixGenerics_1.14.0            
[133] dbplyr_2.4.0                      fastmap_1.1.1                    
[135] ensembldb_2.26.0                  rlang_1.1.2                      
[137] htmlwidgets_1.6.3                 shiny_1.8.0                      
[139] zoo_1.8-12                        jsonlite_1.8.7                   
[141] BiocParallel_1.36.0               R.oo_1.25.0                      
[143] RCurl_1.98-1.13                   magrittr_2.0.3                   
[145] GenomeInfoDbData_1.2.11           dotCall64_1.1-0                  
[147] patchwork_1.1.3                   Rhdf5lib_1.24.0                  
[149] munsell_0.5.0                     Rcpp_1.0.11                      
[151] reticulate_1.34.0                 stringi_1.8.2                    
[153] zlibbioc_1.48.0                   MASS_7.3-60                      
[155] plyr_1.8.9                        parallel_4.3.1                   
[157] listenv_0.9.0                     ggrepel_0.9.4                    
[159] deldir_2.0-2                      CNEr_1.38.0                      
[161] Biostrings_2.70.1                 splines_4.3.1                    
[163] tensor_1.5                        hms_1.1.3                        
[165] BSgenome.Hsapiens.UCSC.hg38_1.4.5 igraph_1.5.1                     
[167] spatstat.geom_3.2-7               RcppHNSW_0.5.0                   
[169] reshape2_1.4.4                    biomaRt_2.58.0                   
[171] stats4_4.3.1                      TFMPvalue_0.0.9                  
[173] XML_3.99-0.15                     BiocManager_1.30.22              
[175] JASPAR2020_0.99.10                tzdb_0.4.0                       
[177] httpuv_1.6.12                     RANN_2.6.1                       
[179] tidyr_1.3.0                       purrr_1.0.2                      
[181] polyclip_1.10-6                   future_1.33.0                    
[183] SeuratData_0.2.2.9001             scattermore_1.2                  
[185] ggplot2_3.4.4                     xtable_1.8-4                     
[187] restfulr_0.0.15                   AnnotationFilter_1.26.0          
[189] RSpectra_0.16-1                   later_1.3.1                      
[191] googledrive_2.1.1                 viridisLite_0.4.2                
[193] tibble_3.2.1                      Azimuth_0.5.0                    
[195] memoise_2.0.1                     AnnotationDbi_1.64.1             
[197] GenomicAlignments_1.38.0          IRanges_2.36.0                   
[199] cluster_2.1.4                     globals_0.16.2

**Comment by alasaa** [comment]
I have suspected the problem of my system. Today, I even formatted my C disk, re-installed the Windows 10 system, re-installed R4.3.2, rtools43-5863-5818, RStudio-2023.01.1-494, Anaconda3-2023.09-0 - Windows - x86_64 (with Python). Then I install packages related with Seurat . Then I restart RStudio, load the object, and only library(Seurat).....and still got: Error in .local(x, na.rm, dims, ...) : object 'CRsparse_colSums' not found

**Comment by sameet** [comment]
I initially did not have this problem with `5.0.0`, but definitely had this once it was upgraded to `5.0.1`.  I am trying to analyse  GEX + ATAC but when I try to use the `CreateSeuratObject` function I run into this error.  It is kind of stopping the work.

**Comment by Gesmira** [comment]
Hi all, I have posted an issue documenting this error here: https://github.com/ge11232002/TFBSTools/issues/37. It appears that if `Signac`'s 'suggests' or `Azimuth`'s 'imports' are loaded this error will arise due to a specific package dependency. Until we figure it out, I would restart your R session and avoid loading in either of these packages. If you find that even without loading any packages except for Seurat you get this error, please include a reproducible example with `pbmc3k` from `SeuratData` (example in the issue I posted for how to do this).

**Comment by NaviedA** [comment]
Why not just roll back Matrix to 1.6-1 instead if it's a Matrix library issue?

**Comment by sameet** [comment]
Hi,

I don't think it is just that. I do believe that the answer lies somewhere
in the Azimuth code base.

Sameet

**Comment by annstrange** [comment]
RE: "Why not just roll back Matrix to 1.6-1 instead if it's a Matrix library issue?"  
I tried rolling back Matrix to 1.6-1 or 1.6-2 but then Seurat v5.0.1 will fail: 
 namespace 'Matrix' 1.6-2 is already loaded, but >= 1.6.3 is required

**Comment by NaviedA** [comment]
> RE: "Why not just roll back Matrix to 1.6-1 instead if it's a Matrix library issue?" I tried rolling back Matrix to 1.6-1 or 1.6-2 but then Seurat v5.0.1 will fail: namespace 'Matrix' 1.6-2 is already loaded, but >= 1.6.3 is required

I just rolled back everything to the most recent session I had that worked... if Seurat v5 has this many issues no reason to be using it for now.

**Comment by alasaa** [comment]
> I don't think it is just that. I do believe that the answer lies somewhere in the Azimuth code base.

Thank you very much! And thank you to everyone who responded! The problem maybe caused by the Azimuth package. I uninstalled and reinstalled R4.3.2, then manually removed the Azimuth package and avoid library(Azimuth) , then RunUMAP() can work.

**Comment by Gesmira** [comment]
Hi all, 
A solution is provided here: https://github.com/satijalab/seurat/issues/8089#issuecomment-1847816493

**Comment by FionaMoon** [comment]
Hi all,
I also meet this error if I load `Azimuth` package.
If you're aiming to use the `RunAzimuth` function which is mentioned in the Seurat pipeline without loading the full package, here's a local execution approach, which involves some code modifications:

1. Source the necessary functions:
Create an R script (e.g., azimuth_functions.R) and copy the source code of these functions into it:
`NNTransform`
`LoadReference`
`RunAzimuth.Seurat`
Within your main R script, use source("azimuth_functions.R") to load these functions.

2. download reference
Ensure you have the required reference data for RunAzimuth downloaded and accessible in the appropriate location.

3. Execute RunAzimuth locally:
You can now call RunAzimuth directly in your script, working with the modified functions.

I hope this may help.

**Comment by WUWEIERXUE** [comment]
Try to uninstall "TFBSTools" R package and use "Seurat 4.2.1" to solve the problem.

**Comment by witchhead** [comment]
I installed re installed R Seurat and BioConductor multiple times.
Updated individual packages including irlba and Matrix.
Updated the whole Bioconductor package.
However, the RunAzimuth function always results in the same error
Error in .local(x, na.rm, dims, ...) : 
  object 'CRsparse_colSums' not found

None of the above error seems to solve the problem.
Is there any known perfect setup that doesn't result in any issues?

R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Azimuth_0.5.0            shinyBS_0.61.1           patchwork_1.2.0          pbmcsca.SeuratData_3.0.0 pbmcref.SeuratData_1.0.0 pbmc3k.SeuratData_3.1.4  panc8.SeuratData_3.0.2   ifnb.SeuratData_3.1.0   
 [9] SeuratData_0.2.2.9001    Seurat_5.0.3             SeuratObject_5.0.1       sp_2.1-3                 lubridate_1.9.3          forcats_1.0.0            stringr_1.5.1            dplyr_1.1.4             
[17] purrr_1.0.2              readr_2.1.5              tidyr_1.3.1              tibble_3.2.1             ggplot2_3.5.0            tidyverse_2.0.0         

loaded via a namespace (and not attached):
  [1] fs_1.6.3                          ProtGenerics_1.34.0               matrixStats_1.3.0                 spatstat.sparse_3.0-3             bitops_1.0-7                      DirichletMultinomial_1.44.0      
  [7] TFBSTools_1.40.0                  httr_1.4.7                        RColorBrewer_1.1-3                tools_4.3.3                       sctransform_0.4.1                 utf8_1.2.4                       
 [13] R6_2.5.1                          DT_0.33                           lazyeval_0.2.2                    uwot_0.2.1                        rhdf5filters_1.14.1               withr_3.0.0                      
 [19] prettyunits_1.2.0                 gridExtra_2.3                     progressr_0.14.0                  cli_3.6.2                         Biobase_2.62.0                    spatstat.explore_3.2-7           
 [25] fastDummies_1.7.3                 EnsDb.Hsapiens.v86_2.99.0         shinyjs_2.1.0                     spatstat.data_3.0-4               ggridges_0.5.6                    pbapply_1.7-2                    
 [31] Rsamtools_2.18.0                  R.utils_2.12.3                    parallelly_1.37.1                 BSgenome_1.70.2                   rstudioapi_0.16.0                 RSQLite_2.3.6                    
 [37] generics_0.1.3                    BiocIO_1.12.0                     gtools_3.9.5                      ica_1.0-3                         spatstat.random_3.2-3             googlesheets4_1.1.1              
 [43] GO.db_3.18.0                      Matrix_1.6-5                      fansi_1.0.6                       S4Vectors_0.40.2                  abind_1.4-5                       R.methodsS3_1.8.2                
 [49] lifecycle_1.0.4                   yaml_2.3.8                        SummarizedExperiment_1.32.0       rhdf5_2.46.1                      SparseArray_1.2.4                 BiocFileCache_2.10.2             
 [55] Rtsne_0.17                        grid_4.3.3                        blob_1.2.4                        promises_1.3.0                    shinydashboard_0.7.2              crayon_1.5.2                     
 [61] miniUI_0.1.1.1                    lattice_0.22-6                    cowplot_1.1.3                     annotate_1.80.0                   GenomicFeatures_1.54.4            KEGGREST_1.42.0                  
 [67] pillar_1.9.0                      knitr_1.46                        GenomicRanges_1.54.1              rjson_0.2.21                      future.apply_1.11.2               codetools_0.2-20                 
 [73] fastmatch_1.1-4                   leiden_0.4.3.1                    glue_1.7.0                        data.table_1.15.4                 vctrs_0.6.5                       png_0.1-8                        
 [79] spam_2.10-0                       cellranger_1.1.0                  poweRlaw_0.80.0                   gtable_0.3.4                      cachem_1.0.8                      xfun_0.43                        
 [85] Signac_1.13.0                     S4Arrays_1.2.1                    mime_0.12                         pracma_2.4.4                      survival_3.5-8                    gargle_1.5.2                     
 [91] RcppRoll_0.3.0                    fitdistrplus_1.1-11               ROCR_1.0-11                       nlme_3.1-164                      bit64_4.0.5                       progress_1.2.3                   
 [97] filelock_1.0.3                    RcppAnnoy_0.0.22                  GenomeInfoDb_1.38.8               irlba_2.3.5.1                     KernSmooth_2.23-22                SeuratDisk_0.0.0.9021            
[103] colorspace_2.1-0                  seqLogo_1.68.0                    BiocGenerics_0.48.1               DBI_1.2.2                         tidyselect_1.2.1                  bit_4.0.5                        
[109] compiler_4.3.3                    curl_5.2.1                        hdf5r_1.3.10                      xml2_1.3.6                        DelayedArray_0.28.0               plotly_4.10.4                    
[115] rtracklayer_1.62.0                scales_1.3.0                      caTools_1.18.2                    lmtest_0.9-40                     rappdirs_0.3.3                    digest_0.6.35                    
[121] goftest_1.2-3                     presto_1.0.0                      spatstat.utils_3.0-4              rmarkdown_2.26                    XVector_0.42.0                    htmltools_0.5.8.1                
[127] pkgconfig_2.0.3                   MatrixGenerics_1.14.0             dbplyr_2.5.0                      fastmap_1.1.1                     ensembldb_2.26.0                  rlang_1.1.3                      
[133] htmlwidgets_1.6.4                 shiny_1.8.1.1                     zoo_1.8-12                        jsonlite_1.8.8                    BiocParallel_1.36.0               R.oo_1.26.0                      
[139] RCurl_1.98-1.14                   magrittr_2.0.3                    GenomeInfoDbData_1.2.11           dotCall64_1.1-1                   Rhdf5lib_1.24.2                   munsell_0.5.1                    
[145] Rcpp_1.0.12                       reticulate_1.36.0                 stringi_1.8.3                     zlibbioc_1.48.2                   MASS_7.3-60.0.1                   plyr_1.8.9                       
[151] parallel_4.3.3                    listenv_0.9.1                     ggrepel_0.9.5                     CNEr_1.38.0                       deldir_2.0-4                      Biostrings_2.70.3                
[157] splines_4.3.3                     tensor_1.5                        hms_1.1.3                         BSgenome.Hsapiens.UCSC.hg38_1.4.5 igraph_2.0.3                      spatstat.geom_3.2-9              
[163] RcppHNSW_0.6.0                    reshape2_1.4.4                    biomaRt_2.58.2                    stats4_4.3.3                      TFMPvalue_0.0.9                   XML_3.99-0.16.1                  
[169] evaluate_0.23                     BiocManager_1.30.22               JASPAR2020_0.99.10                tzdb_0.4.0                        httpuv_1.6.15                     RANN_2.6.1                       
[175] polyclip_1.10-6                   future_1.33.2                     scattermore_1.2                   xtable_1.8-4                      restfulr_0.0.15                   AnnotationFilter_1.26.0          
[181] RSpectra_0.16-1                   later_1.3.2                       googledrive_2.1.1                 viridisLite_0.4.2                 memoise_2.0.1                     AnnotationDbi_1.64.1             
[187] GenomicAlignments_1.38.2          IRanges_2.36.0                    cluster_2.1.6                     timechange_0.3.0                  globals_0.16.3

**Comment by NaviedA** [comment]
> I installed re installed R Seurat and BioConductor multiple times. Updated individual packages including irlba and Matrix. Updated the whole Bioconductor package. However, the RunAzimuth function always results in the same error Error in .local(x, na.rm, dims, ...) : object 'CRsparse_colSums' not found
> 
> None of the above error seems to solve the problem. Is there any known perfect setup that doesn't result in any issues?
> 
> R version 4.3.3 (2024-02-29 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 19045)
> 
> Matrix products: default
> 
> locale: [1] LC_COLLATE=English_United States.utf8 LC_CTYPE=English_United States.utf8 LC_MONETARY=English_United States.utf8 LC_NUMERIC=C LC_TIME=English_United States.utf8
> 
> time zone: America/New_York tzcode source: internal
> 
> attached base packages: [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages: [1] Azimuth_0.5.0 shinyBS_0.61.1 patchwork_1.2.0 pbmcsca.SeuratData_3.0.0 pbmcref.SeuratData_1.0.0 pbmc3k.SeuratData_3.1.4 panc8.SeuratData_3.0.2 ifnb.SeuratData_3.1.0 [9] SeuratData_0.2.2.9001 Seurat_5.0.3 SeuratObject_5.0.1 sp_2.1-3 lubridate_1.9.3 forcats_1.0.0 stringr_1.5.1 dplyr_1.1.4 [17] purrr_1.0.2 readr_2.1.5 tidyr_1.3.1 tibble_3.2.1 ggplot2_3.5.0 tidyverse_2.0.0
> 
> loaded via a namespace (and not attached): [1] fs_1.6.3 ProtGenerics_1.34.0 matrixStats_1.3.0 spatstat.sparse_3.0-3 bitops_1.0-7 DirichletMultinomial_1.44.0 [7] TFBSTools_1.40.0 httr_1.4.7 RColorBrewer_1.1-3 tools_4.3.3 sctransform_0.4.1 utf8_1.2.4 [13] R6_2.5.1 DT_0.33 lazyeval_0.2.2 uwot_0.2.1 rhdf5filters_1.14.1 withr_3.0.0 [19] prettyunits_1.2.0 gridExtra_2.3 progressr_0.14.0 cli_3.6.2 Biobase_2.62.0 spatstat.explore_3.2-7 [25] fastDummies_1.7.3 EnsDb.Hsapiens.v86_2.99.0 shinyjs_2.1.0 spatstat.data_3.0-4 ggridges_0.5.6 pbapply_1.7-2 [31] Rsamtools_2.18.0 R.utils_2.12.3 parallelly_1.37.1 BSgenome_1.70.2 rstudioapi_0.16.0 RSQLite_2.3.6 [37] generics_0.1.3 BiocIO_1.12.0 gtools_3.9.5 ica_1.0-3 spatstat.random_3.2-3 googlesheets4_1.1.1 [43] GO.db_3.18.0 Matrix_1.6-5 fansi_1.0.6 S4Vectors_0.40.2 abind_1.4-5 R.methodsS3_1.8.2 [49] lifecycle_1.0.4 yaml_2.3.8 SummarizedExperiment_1.32.0 rhdf5_2.46.1 SparseArray_1.2.4 BiocFileCache_2.10.2 [55] Rtsne_0.17 grid_4.3.3 blob_1.2.4 promises_1.3.0 shinydashboard_0.7.2 crayon_1.5.2 [61] miniUI_0.1.1.1 lattice_0.22-6 cowplot_1.1.3 annotate_1.80.0 GenomicFeatures_1.54.4 KEGGREST_1.42.0 [67] pillar_1.9.0 knitr_1.46 GenomicRanges_1.54.1 rjson_0.2.21 future.apply_1.11.2 codetools_0.2-20 [73] fastmatch_1.1-4 leiden_0.4.3.1 glue_1.7.0 data.table_1.15.4 vctrs_0.6.5 png_0.1-8 [79] spam_2.10-0 cellranger_1.1.0 poweRlaw_0.80.0 gtable_0.3.4 cachem_1.0.8 xfun_0.43 [85] Signac_1.13.0 S4Arrays_1.2.1 mime_0.12 pracma_2.4.4 survival_3.5-8 gargle_1.5.2 [91] RcppRoll_0.3.0 fitdistrplus_1.1-11 ROCR_1.0-11 nlme_3.1-164 bit64_4.0.5 progress_1.2.3 [97] filelock_1.0.3 RcppAnnoy_0.0.22 GenomeInfoDb_1.38.8 irlba_2.3.5.1 KernSmooth_2.23-22 SeuratDisk_0.0.0.9021 [103] colorspace_2.1-0 seqLogo_1.68.0 BiocGenerics_0.48.1 DBI_1.2.2 tidyselect_1.2.1 bit_4.0.5 [109] compiler_4.3.3 curl_5.2.1 hdf5r_1.3.10 xml2_1.3.6 DelayedArray_0.28.0 plotly_4.10.4 [115] rtracklayer_1.62.0 scales_1.3.0 caTools_1.18.2 lmtest_0.9-40 rappdirs_0.3.3 digest_0.6.35 [121] goftest_1.2-3 presto_1.0.0 spatstat.utils_3.0-4 rmarkdown_2.26 XVector_0.42.0 htmltools_0.5.8.1 [127] pkgconfig_2.0.3 MatrixGenerics_1.14.0 dbplyr_2.5.0 fastmap_1.1.1 ensembldb_2.26.0 rlang_1.1.3 [133] htmlwidgets_1.6.4 shiny_1.8.1.1 zoo_1.8-12 jsonlite_1.8.8 BiocParallel_1.36.0 R.oo_1.26.0 [139] RCurl_1.98-1.14 magrittr_2.0.3 GenomeInfoDbData_1.2.11 dotCall64_1.1-1 Rhdf5lib_1.24.2 munsell_0.5.1 [145] Rcpp_1.0.12 reticulate_1.36.0 stringi_1.8.3 zlibbioc_1.48.2 MASS_7.3-60.0.1 plyr_1.8.9 [151] parallel_4.3.3 listenv_0.9.1 ggrepel_0.9.5 CNEr_1.38.0 deldir_2.0-4 Biostrings_2.70.3 [157] splines_4.3.3 tensor_1.5 hms_1.1.3 BSgenome.Hsapiens.UCSC.hg38_1.4.5 igraph_2.0.3 spatstat.geom_3.2-9 [163] RcppHNSW_0.6.0 reshape2_1.4.4 biomaRt_2.58.2 stats4_4.3.3 TFMPvalue_0.0.9 XML_3.99-0.16.1 [169] evaluate_0.23 BiocManager_1.30.22 JASPAR2020_0.99.10 tzdb_0.4.0 httpuv_1.6.15 RANN_2.6.1 [175] polyclip_1.10-6 future_1.33.2 scattermore_1.2 xtable_1.8-4 restfulr_0.0.15 AnnotationFilter_1.26.0 [181] RSpectra_0.16-1 later_1.3.2 googledrive_2.1.1 viridisLite_0.4.2 memoise_2.0.1 AnnotationDbi_1.64.1 [187] GenomicAlignments_1.38.2 IRanges_2.36.0 cluster_2.1.6 timechange_0.3.0 globals_0.16.3

As stated above, the actual soln involves problems with TFBSTools, which you have loaded: https://github.com/satijalab/seurat/issues/8202#issue-2047511055

**Comment by ruitanwang** [comment]
> 2\. update.packages()

Thank you.It is so useful for me.
