### ISSUE TITLE
14 warnings from HarmonyIntegration in Seurat v5 integration

### ISSUE THREAD

**Issue by MWRR** [satijalab/seurat#8162]
After running the HarmonyIntegration to integrate a large dataset (94 samples) 
`Seu.object <- IntegrateLayers(
 object = Seu.object, method = HarmonyIntegration, orig.reduction = "pca", new.reduction "harmony",
 verbose = FALSE
)`
it worked fine but I got 14 warnings

> Warning messages:
1: HarmonyMatrix is deprecated and will be removed in the future from the API in the future
2: Warning: The parameters do_pca and npcs are deprecated. They will be ignored for this function call and please remove parameters do_pca and npcs and pass to harmony cell_embeddings directly.
This warning is displayed once per session.
3: Warning: The parameter tau is deprecated. It will be ignored for this function call and please remove parameter tau in future function calls. Advanced users can set value of parameter tau by using parameter .options and function harmony_options().
This warning is displayed once per session.
4: Warning: The parameter block.size is deprecated. It will be ignored for this function call and please remove parameter block.size in future function calls. Advanced users can set value of parameter block.size by using parameter .options and function harmony_options().
This warning is displayed once per session.
5: Warning: The parameter max.iter.harmony is replaced with parameter max_iter. It will be ignored for this function call and please use parameter max_iter in future function calls.
This warning is displayed once per session.
6: Warning: The parameter max.iter.cluster is deprecated. It will be ignored for this function call and please remove parameter max.iter.cluster in future function calls. Advanced users can set value of parameter max.iter.cluster by using parameter .options and function harmony_options().
This warning is displayed once per session.
7: Warning: The parameter epsilon.cluster is deprecated. It will be ignored for this function call and please remove parameter epsilon.cluster in future function calls. Advanced users can set value of parameter epsilon.cluster by using parameter .options and function harmony_options().
This warning is displayed once per session.
8: Warning: The parameter epsilon.harmony is deprecated. It will be ignored for this function call and please remove parameter epsilon.harmony in future function calls. If users want to control if harmony would stop early or not, use parameter early_stop. Advanced users can set value of parameter epsilon.harmony by using parameter .options and function harmony_options().
This warning is displayed once per session.
9: Quick-TRANSfer stage steps exceeded maximum (= 24562400)
10: Quick-TRANSfer stage steps exceeded maximum (= 24562400)
11: Quick-TRANSfer stage steps exceeded maximum (= 24562400)
12: Quick-TRANSfer stage steps exceeded maximum (= 24562400)
13: Quick-TRANSfer stage steps exceeded maximum (= 24562400)
14: Quick-TRANSfer stage steps exceeded maximum (= 24562400)

> 

Will this affect the analysis' result or they are just warnings that would be ignored?
I am using Seurat V 5.0.1.

**Comment by mhkowalski** [comment]
Thanks for reporting this. This is all fine. We're working on fixing this so the warnings won't come up, but this should not affect your results.

**Comment by bebejhun** [comment]
I'm having a problem with this right now.

when I run this code,

obj <- IntegrateLayers(object = obj, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = "harmony", verbose = FALSE)

I always got a warning message and it doesn't appeared the code run properly.

Warning: HarmonyMatrix is deprecated and will be removed in the future from the API in the future

**Comment by igrabski** [comment]
Hi, since this issue is about the warnings which we have addressed above, I will close this issue. If you are having a different problem, please feel free to open a new issue with the details below:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

**Comment by BenjaminDEMAILLE** [comment]
Not solved > Crohn <- IntegrateLayers(
+   object = Crohn, 
+   method = HarmonyIntegration, 
+   normalization.method = "SCT", 
+   orig.reduction = "pca", 
+   new.reduction = "harmony",
+   verbose = T
+ )
Warning in harmony::HarmonyMatrix(data_mat = Embeddings(object = orig),  :
  HarmonyMatrix is deprecated and will be removed in the future from the API in the future
Warning: Warning: The parameters do_pca and npcs are deprecated. They will be ignored for this function call and please remove parameters do_pca and npcs and pass to harmony cell_embeddings directly.
This warning is displayed once per session.
Warning: Warning: The parameter tau is deprecated. It will be ignored for this function call and please remove parameter tau in future function calls. Advanced users can set value of parameter tau by using parameter .options and function harmony_options().
This warning is displayed once per session.
Warning: Warning: The parameter block.size is deprecated. It will be ignored for this function call and please remove parameter block.size in future function calls. Advanced users can set value of parameter block.size by using parameter .options and function harmony_options().
This warning is displayed once per session.
Warning: Warning: The parameter max.iter.harmony is replaced with parameter max_iter. It will be ignored for this function call and please use parameter max_iter in future function calls.
This warning is displayed once per session.
Warning: Warning: The parameter max.iter.cluster is deprecated. It will be ignored for this function call and please remove parameter max.iter.cluster in future function calls. Advanced users can set value of parameter max.iter.cluster by using parameter .options and function harmony_options().
This warning is displayed once per session.
Warning: Warning: The parameter epsilon.cluster is deprecated. It will be ignored for this function call and please remove parameter epsilon.cluster in future function calls. Advanced users can set value of parameter epsilon.cluster by using parameter .options and function harmony_options().
This warning is displayed once per session.
Warning: Warning: The parameter epsilon.harmony is deprecated. It will be ignored for this function call and please remove parameter epsilon.harmony in future function calls. If users want to control if harmony would stop early or not, use parameter early_stop. Advanced users can set value of parameter epsilon.harmony by using parameter .options and function harmony_options().
This warning is displayed once per session.
Transposing data matrix
Using automatic lambda estimation
Initializing state using k-means centroids initialization
Warning: Quick-TRANSfer stage steps exceeded maximum (= 10100650)
Warning: Quick-TRANSfer stage steps exceeded maximum (= 10100650)
Warning: Quick-TRANSfer stage steps exceeded maximum (= 10100650)
Warning: Quick-TRANSfer stage steps exceeded maximum (= 10100650)
Warning: Quick-TRANSfer stage steps exceeded maximum (= 10100650)
Warning: Quick-TRANSfer stage steps exceeded maximum (= 10100650)

**Comment by yeroslaviz** [comment]
Still not solved. DO we need a newer version of harmony/Seurat?

```
Warning in harmony::HarmonyMatrix(data_mat = Embeddings(object = orig),  :
  HarmonyMatrix is deprecated and will be removed in the future from the API in the future
Warning: Warning: The parameters do_pca and npcs are deprecated. They will be ignored for this function call and please remove parameters do_pca and npcs and pass to harmony cell_embeddings directly.
This warning is displayed once per session.

Warning: Warning: The parameter tau is deprecated. It will be ignored for this function call and please remove parameter tau in future function calls. Advanced users can set value of parameter tau by using parameter .options and function harmony_options().
This warning is displayed once per session.

Warning: Warning: The parameter block.size is deprecated. It will be ignored for this function call and please remove parameter block.size in future function calls. Advanced users can set value of parameter block.size by using parameter .options and function harmony_options().
This warning is displayed once per session.

Warning: Warning: The parameter max.iter.harmony is replaced with parameter max_iter. It will be ignored for this function call and please use parameter max_iter in future function calls.
This warning is displayed once per session.

Warning: Warning: The parameter max.iter.cluster is deprecated. It will be ignored for this function call and please remove parameter max.iter.cluster in future function calls. Advanced users can set value of parameter max.iter.cluster by using parameter .options and function harmony_options().
This warning is displayed once per session.

Warning: Warning: The parameter epsilon.cluster is deprecated. It will be ignored for this function call and please remove parameter epsilon.cluster in future function calls. Advanced users can set value of parameter epsilon.cluster by using parameter .options and function harmony_options().
This warning is displayed once per session.

Warning: Warning: The parameter epsilon.harmony is deprecated. It will be ignored for this function call and please remove parameter epsilon.harmony in future function calls. If users want to control if harmony would stop early or not, use parameter early_stop. Advanced users can set value of parameter epsilon.harmony by using parameter .options and function harmony_options().
This warning is displayed once per session.
```
