### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

### ISSUE THREAD

**Issue by Noralii** [satijalab/seurat#8916]
data_combined <- RunFastMNN(object.list = SplitObject(data_combined, split.by = "orig.ident"))
Computing 2000 integration features
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

**Comment by ZhangRuifen** [comment]
I've solved the question by the below codes:
```
filter_genes <- function(seurat_obj) {
  seurat_obj <- subset(seurat_obj, features = integ_features)
  return(seurat_obj)
}
filtered_seurat_list <- lapply(Epi.list, filter_genes)
```
As you see, I just make the rownames(Epi.list) = integ_features, after that Every thing become so smoothly like that:
# step 3
integ_anchors <- FindIntegrationAnchors(object.list = Epi.list, anchor.features = integ_features, normalization.method = "SCT", reduction = "cca")
```
```
# step 4
obj.combined <- IntegrateData(anchorset = integ_anchors, normalization.method = "SCT") 
```
So, the most important thing is to justify both of this two object's rownames are the same as each other.

**Comment by beazors** [comment]
@ZhangRuifen Thanks for your code. I had the same issue as the OP, tried your code, and ran into an issue at the last step again (IntegrateData). 

```
>  pbmc.integrated <- IntegrateData(anchorset = integ_anchors,normalization.method="SCT")
[1] 1
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 2
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 3
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 4
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 5
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 6
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 7
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 8
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 9
Warning: Layer counts isn't present in the assay object; returning NULL
[1] 10
Warning: Layer counts isn't present in the assay object; returning NULL
Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Warning: Layer counts isn't present in the assay object; returning NULL
Merging dataset 7 into 5
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Warning: Layer counts isn't present in the assay object; returning NULL
Merging dataset 10 into 8
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|(etc)
```

Additionally, for anyone: I'm confused as to how this line of code (IntegrateData) knows to perform integration on the correct object (the list of datasets) if it is not fed into it. It looks like it's only the anchor set and normalization method that goes in.

**Comment by ZhangRuifen** [comment]
@beazors Hi! I'm not sure whether you have done with JoinLayers() to your Seurat object. And did you get your integrated object? It seems no errors but only warnings, you can check what you have got.

**Comment by beazors** [comment]
@ZhangRuifen I did get an object, but I'm not sure how to evaluate if it's worked or what to do with the object next. Normally I have merged all my data first and run everything downstream of that (not in list form). 

As for JoinLayers(), which object would you try to join? I tried it on the equivalent objects to your Epi.list, obj.combined, and integ_anchors, and all got the same error. Error in UseMethod(generic = "JoinLayers", object = object) : 
  no applicable method for 'JoinLayers' applied to an object of class "list" (or c("x","y","z")).

**Comment by drroya** [comment]
I think it may be something with the newest seurat version (for me 5.1.0)??
Because I am running the same codes in a different computer without any error! The exact same code.

**Comment by Hannah-Doerpholz** [comment]
I had the same error message when trying to run SelectIntegrationFeatures on my split seurat object. I downgraded r-seurat (I'm working with conda) to 5.0.3, but that didn't solve the issue. I then also downgraded r-seuratobject to 5.0.1 and that solved the issue for me.

**Comment by drroya** [comment]
@Hannah-Doerpholz

Thank you for sharing the solution.
Can you kindly share the code you use for downgrading. For me it weirdly doesn't work!

**Comment by Hannah-Doerpholz** [comment]
@drroya Since I am doing everything in a conda environment I ran the following in the terminal:
```
conda activate seurat_env
conda install r-seurat=5.0.3
conda install r-seuratobject=5.0.1
```
I didn't need to remove the previous version for that as it just downgraded them.
If you don't use conda this should work for you if you do it with R:
```
install.packages("remotes")
library(remotes)
remotes::install_version("Seurat", version="5.0.3")
remotes::install_version("SeuratObject", version="5.0.1")
```
When prompted, I chose to not update anything else.
Maybe you might need to remove the old packages before, if you encounter some errors. For me it worked without removing anything:
```
remove.packages("Seurat")
remove.packages("SeuratObject")
```

**Comment by drroya** [comment]
@Hannah-Doerpholz

Many thanks for your reply and the detailed codes!

**Comment by ZhangRuifen** [comment]
@beazors Sorry to reply late! I'm happy that you have sovle your question! But I see the link you mentioned, I don't think it's any different than our code, but it still solved the problem. It's made me a little confused.

**Comment by longmanz** [comment]
Hi,
Thank you all for reporting this issue. Can anyone kindly provide us with a reproducible example + a small test dataset so that we can look into this? In addition, does this issue still persists if you switch to the Seurat V5 integration pipeline ([IntegrateLayers](https://satijalab.org/seurat/reference/integratelayers))? Or it only occurs when you run IntegrateData() ?

**Comment by HumaNaz0011** [comment]
Hi team!
I am reintegrating RNA and ATAC object(after removal of doublets). ATAC part is done but at RNA object , I am not able to perform IntegrateData step. I will really appreciate your help.

below are my codes and session information.

```
#Re-integrate RNA
DefaultAssay(cleanObj1) <- "RNA"



obj_rna <- DietSeurat(
  object =cleanObj1,
  counts = TRUE,
  data = TRUE,
  scale.data = FALSE,
  assays = "RNA"
)

#integrate objects
obj.list <- SplitObject(obj_rna, split.by = "orig.ident")

#####integrated analysis to remove batch effects########## 

for (i in 1:length(obj.list)) {
  obj.list[[i]] <- SCTransform(obj.list[[i]],  vars.to.regress = c("nCount_RNA", "percent.mt"),verbose = FALSE)
}
#adjust max memory for global environment
options(future.globals.maxSize= 5368709120^10)

###integrate data
alldata.features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 3000)
alldata_prepsct <- PrepSCTIntegration(object.list = obj.list, anchor.features = alldata.features, verbose = FALSE)

alldata.anchors <- FindIntegrationAnchors(object.list = alldata_prepsct, normalization.method = "SCT", anchor.features = alldata.features, verbose = FALSE)

data_integrated <- IntegrateData(anchorset = alldata.anchors, normalization.method = "SCT", verbose = FALSE)

 Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
```

my session info is

```
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] irlba_2.3.5.1                     Matrix_1.6-5                      RSpectra_0.16-2                  
 [4] data.table_1.16.4                 ggrepel_0.9.6                     Hmisc_5.2-2                      
 [7] gplots_3.2.0                      RColorBrewer_1.1-3                reshape2_1.4.4                   
[10] lubridate_1.9.4                   forcats_1.0.0                     stringr_1.5.1                    
[13] purrr_1.0.4                       tidyr_1.3.1                       tibble_3.2.1                     
[16] tidyverse_2.0.0                   readr_2.1.5                       sctransform_0.4.1                
[19] metap_1.11                        cowplot_1.1.3                     future_1.34.0                    
[22] EnsDb.Hsapiens.v86_2.99.0         ensembldb_2.26.0                  AnnotationFilter_1.26.0          
[25] GenomicFeatures_1.54.4            AnnotationDbi_1.64.1              Biobase_2.62.0                   
[28] BSgenome.Hsapiens.UCSC.hg38_1.4.5 BSgenome_1.70.2                   BiocIO_1.12.0                    
[31] Biostrings_2.70.3                 XVector_0.42.0                    rtracklayer_1.62.0               
[34] patchwork_1.3.0                   ggplot2_3.5.1                     dplyr_1.1.4                      
[37] Seurat_5.2.1                      Signac_1.14.0                     SeuratObject_5.0.2               
[40] sp_2.2-0                          GenomicRanges_1.54.1              GenomeInfoDb_1.38.8              
[43] IRanges_2.36.0                    S4Vectors_0.40.2                  BiocGenerics_0.48.1              

loaded via a namespace (and not attached):
  [1] ProtGenerics_1.34.0         matrixStats_1.5.0           spatstat.sparse_3.1-0       bitops_1.0-9               
  [5] httr_1.4.7                  numDeriv_2016.8-1.1         backports_1.5.0             tools_4.3.2                
  [9] R6_2.5.1                    lazyeval_0.2.2              uwot_0.2.2                  sn_2.1.1                   
 [13] withr_3.0.2                 prettyunits_1.2.0           gridExtra_2.3               progressr_0.15.1           
 [17] cli_3.6.3                   spatstat.explore_3.3-4      fastDummies_1.7.5           sandwich_3.1-1             
 [21] mvtnorm_1.3-3               spatstat.data_3.1-4         ggridges_0.5.6              pbapply_1.7-2              
 [25] Rsamtools_2.18.0            foreign_0.8-88              parallelly_1.42.0           plotrix_3.8-4              
 [29] rstudioapi_0.17.1           RSQLite_2.3.9               generics_0.1.3              gtools_3.9.5               
 [33] ica_1.0-3                   spatstat.random_3.3-2       abind_1.4-8                 lifecycle_1.0.4            
 [37] multcomp_1.4-28             yaml_2.3.10                 SummarizedExperiment_1.32.0 mathjaxr_1.6-0             
 [41] glmGamPoi_1.14.3            SparseArray_1.2.4           BiocFileCache_2.10.2        Rtsne_0.17                 
 [45] grid_4.3.2                  blob_1.2.4                  promises_1.3.2              crayon_1.5.3               
 [49] miniUI_0.1.1.1              lattice_0.22-6              KEGGREST_1.42.0             pillar_1.10.1              
 [53] knitr_1.49                  rjson_0.2.23                future.apply_1.11.3         codetools_0.2-20           
 [57] fastmatch_1.1-6             mutoss_0.1-13               glue_1.8.0                  spatstat.univar_3.1-1      
 [61] vctrs_0.6.5                 png_0.1-8                   spam_2.11-1                 Rdpack_2.6.2               
 [65] gtable_0.3.6                cachem_1.1.0                xfun_0.50                   rbibutils_2.3              
 [69] S4Arrays_1.2.1              mime_0.12                   survival_3.8-3              RcppRoll_0.3.1             
 [73] fitdistrplus_1.2-2          TH.data_1.1-3               ROCR_1.0-11                 nlme_3.1-167               
 [77] bit64_4.6.0-1               progress_1.2.3              filelock_1.0.3              RcppAnnoy_0.0.22           
 [81] rpart_4.1.24                KernSmooth_2.23-26          colorspace_2.1-1            DBI_1.2.3                  
 [85] nnet_7.3-20                 mnormt_2.1.1                tidyselect_1.2.1            bit_4.5.0.1                
 [89] compiler_4.3.2              curl_6.2.0                  htmlTable_2.4.3             xml2_1.3.6                 
 [93] TFisher_0.2.0               DelayedArray_0.28.0         plotly_4.10.4               checkmate_2.3.2            
 [97] caTools_1.18.3              scales_1.3.0                lmtest_0.9-40               rappdirs_0.3.3             
[101] digest_0.6.37               goftest_1.2-3               spatstat.utils_3.1-2        rmarkdown_2.29             
[105] base64enc_0.1-3             htmltools_0.5.8.1           pkgconfig_2.0.3             sparseMatrixStats_1.14.0   
[109] MatrixGenerics_1.14.0       dbplyr_2.5.0                fastmap_1.2.0               rlang_1.1.5                
[113] htmlwidgets_1.6.4           DelayedMatrixStats_1.24.0   shiny_1.10.0                farver_2.1.2               
[117] zoo_1.8-12                  jsonlite_1.8.9              BiocParallel_1.36.0         RCurl_1.98-1.16            
[121] magrittr_2.0.3              Formula_1.2-5               GenomeInfoDbData_1.2.11     dotCall64_1.2              
[125] munsell_0.5.1               Rcpp_1.0.14                 reticulate_1.40.0           stringi_1.8.4              
[129] zlibbioc_1.48.2             MASS_7.3-60.0.1             plyr_1.8.9                  parallel_4.3.2             
[133] listenv_0.9.1               deldir_2.0-4                splines_4.3.2               tensor_1.5                 
[137] multtest_2.58.0             hms_1.1.3                   qqconf_1.3.2                igraph_2.1.4               
[141] spatstat.geom_3.3-5         RcppHNSW_0.6.0              biomaRt_2.58.2              XML_3.99-0.18              
[145] evaluate_1.0.3              tzdb_0.4.0                  httpuv_1.6.15               RANN_2.6.2                 
[149] polyclip_1.10-7             scattermore_1.2             xtable_1.8-4                restfulr_0.0.15            
[153] later_1.4.1                 viridisLite_0.4.2           memoise_2.0.1               GenomicAlignments_1.38.2   
[157] cluster_2.1.8               timechange_0.3.0            globals_0.16.3  
```

**Comment by Rohit-Satyam** [comment]
I am also facing the same error when post-integration I try to subset the Seurat object.

**Comment by longmanz** [comment]
Closing this as this `subset` issue is fixed in the later versions (>= v5.2).
