### ISSUE TITLE
Warning: Layer counts isn't present in the assay object; returning NULL

### ISSUE THREAD

**Issue by jianguotao** [satijalab/seurat#8938]
I was able to use the fastMNN integration back in February, and now it's reporting errors when I run it. Same data, the R package used to be like 5.0? it seems to have been automatically upgraded to 5.1.0

> sce.big_QC1_LV
An object of class Seurat 
21903 features across 6266 samples within 1 assay 
Active assay: RNA (21903 features, 2000 variable features)
 5 layers present: counts.GSM4677820_Sp7_cKO, counts.GSM4677821_WT, data.GSM4677820_Sp7_cKO, data.GSM4677821_WT, scale.data
 4 dimensional reductions calculated: pca, tsne, umap, integrated.cca

#FastMNN
sce.big_QC1_LV <- IntegrateLayers(
  object = sce.big_QC1_LV, method = FastMNNIntegration,
  new.reduction = "integrated.mnn",
  verbose = FALSE
)

Warning: Layer counts isn't present in the assay object; returning NULL

**Comment by CarlCoyle32** [comment]
I am also seeing this error when running IntegrateData.

**Comment by LaurensV1000** [comment]
I have the same error.

**Comment by scs298** [comment]
me as well

**Comment by cole-aifi** [comment]
I'm seeing this when using TransferData

**Comment by marcoco90** [comment]
Used Transferdata yesterday with no problem. Today I run the same commands on the same samples and got that error message as well

**Comment by kmshort** [comment]
I'll add a "me too" to this. I have 3 seurat5 objects which I'm tring to integrate. SelectIntegrationFeatures works, PrePSCTIntegration works, FindIntegrationAnchors works, but during IntegrateData, I get the 

`Warning: Layer counts isn't present in the assay object; returning NULL`

The SCT and RNA layers in the source objects both have "counts" layers.
The resulting integrated object has an integrated assay that only has 'data' and 'scale.data' layers.
The integrated object also has SCT and RNA assays, and they contain 'counts', 'data' and 'scale.data' layers.

So the warning is real, and the integrated assay has no counts.

regards,
Kieran

**Comment by tmgibs** [comment]
I got the same error, starting from `CalcPerturbSeq()` and using a Seurat object that had its `@counts` slots well and full.

**Comment by feanaros** [comment]
me too

**Comment by BDXH-FY24** [comment]
me too

**Comment by silgoni17** [comment]
Me too

**Comment by aimutishammy** [comment]
Same

**Comment by hanhyebin** [comment]
I also need help with this.

**Comment by sergio-rutella** [comment]
Ditto!

**Comment by AntoniaChroni** [comment]
I get the same error message: `Warning: Layer counts isn't present in the assay object; returning NULL` when 
`seurat_obj <- IntegrateData(anchorset = anchors, normalization.method = "SCT", verbose = TRUE)`. Any insights on what's going on?

**Comment by umutcakir** [comment]
Me too when I am using TransferData

**Comment by zhoujiaqi704** [comment]
same when using IntegrateData

**Comment by anitasalamon** [comment]
I also got this error

**Comment by HOKYOUNGWWW** [comment]
Me too

**Comment by pedrodcb** [comment]
@AntoniaChroni I think so. I was getting this warning too when using the Azimuth package and thanks to your comment I downgraded SeuratObject to version 5.0.1 : `install.packages("https://cran.r-project.org/src/contrib/Archive/SeuratObject/SeuratObject_5.0.1.tar.gz", repos=NULL, type="source")` and everything seems to be working now.

**Comment by rpisalive** [comment]
> @AntoniaChroni I think so. I was getting this warning too when using the Azimuth package and thanks to your comment I downgraded SeuratObject to version 5.0.1 : `install.packages("https://cran.r-project.org/src/contrib/Archive/SeuratObject/SeuratObject_5.0.1.tar.gz", repos=NULL, type="source")` and everything seems to be working now.

May I ask what version of seurat are you using? My Seurat version is 5.1.0 and it showed me the error:
Error: package ‘SeuratObject’ 5.0.1 was found, but >= 5.0.2 is required by ‘Seurat’
when I downgraded SeuratObject to 5.0.1.
I wanted to try Seurat 4.4.0 like @AntoniaChroni suggested but my SeuratObjects are all V5. Currently, I am also experiencing the "Warning: Layer counts isn't present in the assay object; returning NULL" problem and it seems downgrading SeuratObject to 5.0.1 the only feasible solution for me.

**Comment by pedrodcb** [comment]
@rpisalive yes, I'm using version 4.4.0 just like @AntoniaChroni so I can't speak for versions above that. I've noticed another issue that comes up however upon downgrading. It's with the FeaturePlot() function and it's similar to the one described here: #2507. Basically, upon subsetting a Seurat object and running UMAP() on it again, DimPlot() returns the correct UMAP for the subset but FeaturePlot() doesn't. It returns the UMAP for the full object, as if the UMAP reduction was not updated on the latter. Yet DimPlot() detects it. This issue goes away for me if I upgrade SeuratObject to v. 5.0.2 OR if I downgrade it to v. 4.1.4. It is of course also solved by doing what @AlisonCole did on the issue referenced above:

_This is resolved if I give the RunUMAP command a different output name and specify this in the FeaturePlot command:_
```
RunUMAP(newdata, dims = c(1:10), reduction.name = 'umapNew')
FeaturePlot(newdata, 'nFeature_RNA', reduction = 'umapNew') 
```
Just wanted to let people know of this here.

**Comment by rfey** [comment]
Me too, with Seurat_5.1.0 and SeuratObject_5.0.2. I was able to use IntegrateData() successfully a couple of weeks ago with Seurat_5.0.3 and SeuratObject_5.0.1, so I may downgrade both and try again.

**Comment by alg697** [comment]
I am also having this issue while running Seurat 5.1.0

**Comment by tlrQkd** [comment]
I'm also having this issue with the IntegrateData() function. 
I'musing Seurat version 5.1.0

**Comment by alg697** [comment]
Hi everyone, I have figured out how to perform integration with the new 5.1.0 updates. 

I will say caveat, SCT normalization still seems to be causing issues so I have performed standard normalization steps. 

First generate a list of your Seurat objects and then merge them into one object. 

**ser_merged <- merge(ser_list[[1]],y=c(ser_list[2:11]), add.cell.ids = c("1", "10", "11", "2", "3", "4", "5", 
                                                      "6", "7", "8", "9"), project = "GSE173682")**

Then I run the standard analysis for comparison with the integrated object. 

**ser_pre <- ser_merged %>% 
  NormalizeData(.) %>%
  FindVariableFeatures(.) %>%
  ScaleData(.) %>%
  RunPCA(.) %>%
  FindNeighbors(.,dims=1:10, reduction = "pca") %>%
  FindClusters(., resolution = c(0.5)) %>%
  RunUMAP(.,dims=1:10, reduction = "pca")**

The new step in the v5 integration is the use of layers. This step takes the place of IntegrateData() as well as steps for identifying integration features or anchors. 

**ser_int <- IntegrateLayers(object = ser_pre, method = CCAIntegration, orig.reduction = "pca", 
                                            new.reduction="integrated.cca", verbose = FALSE)**

You can then join the layers and proceed with the rest of the analysis. 

ser_int[["RNA"]] <- JoinLayers(ser_int[["RNA"]])

**ser_int <- ser_int %>%
  FindNeighbors(., reduction = "integrated.cca", dims = 1:10) %>%
  FindClusters(.,res=c(0.5), cluster.name = "integrated.clusters") %>%
  RunUMAP(., dims=1:10, reduction= "integrated.cca", reduction.name = "integrated.umap")**

**Comment by FionaMoon** [comment]
My Seurat version is 5.1.0 and I got this error when running `IntegrateLayers`.
One interesting thing is that the error only happens when `method=FastMNNIntegration`.

**Comment by KhadijaSJ** [comment]
> My Seurat version is 5.1.0 and I got this error when running `IntegrateLayers`. One interesting thing is that the error only happens when `method=FastMNNIntegration`.

Same for me

**Comment by eileeeeeeeen** [comment]
> Me too, with Seurat_5.1.0 and SeuratObject_5.0.2. I was able to use IntegrateData() successfully a couple of weeks ago with Seurat_5.0.3 and SeuratObject_5.0.1, so I may downgrade both and try again.

Hi there. so did it work after you downgrade them both?

**Comment by KhadijaSJ** [comment]
> > Me too, with Seurat_5.1.0 and SeuratObject_5.0.2. I was able to use IntegrateData() successfully a couple of weeks ago with Seurat_5.0.3 and SeuratObject_5.0.1, so I may downgrade both and try again.
> 
> Hi there. so did it work after you downgrade them both?

Downgrading to the above mentioned versions worked for me

**Comment by rfey** [comment]
> > Me too, with Seurat_5.1.0 and SeuratObject_5.0.2. I was able to use IntegrateData() successfully a couple of weeks ago with Seurat_5.0.3 and SeuratObject_5.0.1, so I may downgrade both and try again.
> 
> Hi there. so did it work after you downgrade them both?

Yes, downgrading both packages worked for me! I was able to integrate successfully.

**Comment by lindsaynhayes** [comment]
> My Seurat version is 5.1.0 and I got this error when running `IntegrateLayers`. One interesting thing is that the error only happens when `method=FastMNNIntegration`.

It's a warning not an error. The integration is successful. What are the consequences of "Layer counts not present" on the integration? When you look at the object the mnn reduction is present and the resulting umap is different than unintegrated.

**Comment by cetinsz** [comment]
> Hi everyone, I have figured out how to perform integration with the new 5.1.0 updates.
> 
> I will say caveat, SCT normalization still seems to be causing issues so I have performed standard normalization steps.
> 
> First generate a list of your Seurat objects and then merge them into one object.
> 
> **ser_merged <- merge(ser_list[[1]],y=c(ser_list[2:11]), add.cell.ids = c("1", "10", "11", "2", "3", "4", "5", "6", "7", "8", "9"), project = "GSE173682")**
> 
> Then I run the standard analysis for comparison with the integrated object.
> 
> **ser_pre <- ser_merged %>% NormalizeData(.) %>% FindVariableFeatures(.) %>% ScaleData(.) %>% RunPCA(.) %>% FindNeighbors(.,dims=1:10, reduction = "pca") %>% FindClusters(., resolution = c(0.5)) %>% RunUMAP(.,dims=1:10, reduction = "pca")**
> 
> The new step in the v5 integration is the use of layers. This step takes the place of IntegrateData() as well as steps for identifying integration features or anchors.
> 
> **ser_int <- IntegrateLayers(object = ser_pre, method = CCAIntegration, orig.reduction = "pca", new.reduction="integrated.cca", verbose = FALSE)**
> 
> You can then join the layers and proceed with the rest of the analysis.
> 
> ser_int[["RNA"]] <- JoinLayers(ser_int[["RNA"]])
> 
> **ser_int <- ser_int %>% FindNeighbors(., reduction = "integrated.cca", dims = 1:10) %>% FindClusters(.,res=c(0.5), cluster.name = "integrated.clusters") %>% RunUMAP(., dims=1:10, reduction= "integrated.cca", reduction.name = "integrated.umap")**


`aki_combined_list1 <- SplitObject(obj, split.by = "sample")
aki_combined_list1 <- lapply(X = aki_combined_list1, FUN = SCTransform, method = "glmGamPoi")
features <- SelectIntegrationFeatures(object.list = aki_combined_list1, nfeatures = 3000)
filter_genes <- function(obj, features) {
  seurat_obj <- subset(obj, features = features)
  return(obj)
}
aki_combined_list1 <- PrepSCTIntegration(object.list = aki_combined_list1, anchor.features = features)
aki_combined_list1 <- lapply(X = aki_combined_list1, FUN = RunPCA, features = features)
aki.anchors1 <- FindIntegrationAnchors(object.list = aki_combined_list1, normalization.method = "SCT",
                                       anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 5, k.filter = NA)


aki.combined.sct1 <- IntegrateData(anchorset = aki.anchors1, normalization.method = "SCT", dims = 1:30, k.weight = 28)
aki.combined.sct1 <- ScaleData(aki.combined.sct1, verbose = FALSE)
aki.combined.sct1 <- RunPCA(aki.combined.sct1, verbose = FALSE)`

In this case, where should I put JoinLayers?

**Comment by rprins182** [comment]
Have the same issue at the integrating data step. Could only make this work by using Seurat 4.4.0 and SeuratObject 5.0.1. Will keep monitoring this thread for a more permanent solution.

**Comment by rfey** [comment]
> how did you downgrade seurat?

I am using conda to manage my packages, so I updated my conda environment with the downgraded versions specified. I think otherwise you can uninstall the packages and reinstall specifying the downgraded versions?

**Comment by yeroslaviz** [comment]
Downgrading Seurat didn't solve my problem. Did anyone find a solution?

**Comment by carminoski** [comment]
any chance this issue has been solved? I am getting warnings and at the end of the integration , there are many tools that are unusable on the integrated object (SingleR for example) because of the absence of counts layer

**Comment by alg697** [comment]
Update from my previous post, figured out SCT and v5 integration, just need to add an extra flag to IntegrateLayers, **normalization.method = "SCT"**

**Comment by salina142** [comment]
Still getting this error - has there been any updates to this? I'm currently downgrading SeuratObject and Seurat versions, so hoping things work now.

**Comment by Chrisdoan9** [comment]
I have that warning when using: FindTransferAnchors() for Visium data. The result is unexpected plot with no cell.

**Comment by Nubocyte** [comment]
Any update on this? I'm also getting this error.

**Comment by AlonsoOga** [comment]
Wow, it seems that this has been an issue for quite a while. I thought things would be fixed by now. I had this issue in May and the Seurat team never got back to me. It seems that there is no way of doing integration with the Seurat V4 pipeline, which seems to be more robust than IntegrateLayers() in Seurat v5...

**Comment by Chrisdoan9** [comment]
How could we have funding so the team have resource to maintain their tool? Hopefully to get issues resolved faster.

**Comment by sbamopoulos** [comment]
Hello everyone,

I have managed with some difficulty to perform a **projection with an SCTransformed and integrated** dataset, using an archived Seurat version along with the old (v3) workflow. Since I've seen many people struggle with this and haven't found a working solution with sctransformed data, here is my code below.

First, you need to install previous versions of Seurat and SeuratObject, here is the code for installing the versions that worked for me: 
```
install.packages("https://cran.r-project.org/src/contrib/Archive/SeuratObject/SeuratObject_5.0.1.tar.gz", repos=NULL, type="source")
install.packages("https://cran.r-project.org/src/contrib/Archive/Seurat/Seurat_5.0.3.tar.gz", repos=NULL, type="source")
```
Read in your files :
```
reference <- readRDS("path_to_ref.Rds")
querydataset <- readRDS("path_to_query.Rds")
```
Then, you need to perform integration of the reference dataset using the old workflow. 

Split object per sample, normalize and run PCA:
```
reflist <- SplitObject(refdataset, split.by = "SampleID") 
reflist <- lapply(X = reflist, FUN = SCTransform) 
reflist <- lapply(X = reflist, FUN = RunPCA, npcs = 30)  
```
Perform Integration through the old workflow for separate objects:
```
features <- SelectIntegrationFeatures(object.list = reflist, nfeatures = 3000) 
reflist <- PrepSCTIntegration(reflist, assay = "SCT", anchor.features = features)
ref.anchors <- FindIntegrationAnchors(object.list = reflist, anchor.features = features, scale = T,
                                      normalization.method = "SCT", reduction = "rpca")
refdataset <- IntegrateData(anchorset = ref.anchors, normalization.method = "SCT") 
refdataset <- RunPCA(refdataset, assay = "integrated", npcs = 30, reduction.name = "pca_integrated")
refdataset <- FindNeighbors(refdataset, reduction = "pca_integrated", dims = 1:30)
refdataset <- FindClusters(refdataset, cluster.name = "clusters_integrated")
refdataset <- RunUMAP(refdataset, dims = 1:30, reduction = "pca_integrated", reduction.name = "umap_integrated")
```
Perform unintegrated analysis for querydata:
```
querydata <- RunPCA(querydata, npcs = 30, reduction.name = "pca_unintegrated")
querydata <- FindNeighbors(querydata, reduction = "pca_unintegrated", dims = 1:30)
querydata <- FindClusters(querydata, cluster.name = "clusters_unintegrated")
querydata <- RunUMAP(querydata, dims = 1:30, reduction = "pca_unintegrated", reduction.name = "umap_unintegrated")

```
Project refdataset onto querydata:
```
querydata.anchors <- FindTransferAnchors(reference = refdataset, reference.assay = "integrated", reference.reduction = "pca_integrated", 
                                         query = querydata, query.assay = "SCT", 
                                         reduction = "pcaproject", normalization.method = 'SCT', dims = 1:30, verbose = T) 
querydata <- MapQuery(anchorset = querydata.anchors, reference = nucref, query = querydata, refdata = "annotation_ref", new.reduction.name = "pca_ref",)
```
Note: some with large datasets (like me) may struggle with limited RAM being available for their R session. In this case you can increase it like this:
```
options(future.globals.maxSize = 8 * 1e9) 
```

Hope this helps!

Best
Stefan

**Comment by shihsama** [comment]
> Me too, with Seurat_5.1.0 and SeuratObject_5.0.2. I was able to use IntegrateData() successfully a couple of weeks ago with Seurat_5.0.3 and SeuratObject_5.0.1, so I may downgrade both and try again.

Highlight! This really worked, even if I ran RunFastMNN() from SeuratWrappers. This would return a MNN-corrected, reconstructed data matrix, instead of count matrix, which is consistent with the result in the paper proposing MNN. This reconstructed expression matrix is used for downstream PCA and non-linear DR.

It seems Satija lab should fix this bug in V5.2. We hope so.  @

**Comment by taylahgaynor** [comment]
@sbamopoulos thanks for the script. I tried running it but encountered the same issue, sadly. Probably naive, but do I need to rerun SCTransform and RunPCA on the objects again with the older Seurat and SeuratObject versions? 

:( If no, has anyone found another solution?

**Comment by alifarhat40** [comment]
I am getting this same error when trying to integrate scATACseq data using this tutorial [here](https://stuartlab.org/signac/articles/integrate_atac#integration)

Has anyone found a solution for this?

**Comment by SaharBJ** [comment]
> I am getting this same error when trying to integrate scATACseq data using this tutorial [here](https://stuartlab.org/signac/articles/integrate_atac#integration)
> 
> Has anyone found a solution for this?

Hi, I am having the same issue. I am not using multiome data. Downgrading Seurat and SeuratObject does not work for me as Signac requires >v5.0.2 of SeuratObject. I have struggled with the SCT suggestions. Has anyone managed successfully integrate pure snATAC-seq data using this tutorial?

**Comment by crispyC-pwj** [comment]
same error，no solution now？

**Comment by YibiChen** [comment]
I believe the problem is causing by the recent changes in Seurat v5.

> Seurat v5 now includes support for additional assay and data types, including on-disk matrices. To facilitate this, we have introduced an updated Seurat v5 assay. Users can check out this [vignette for more information]. Briefly, Seurat v5 assays store data in layers (previously referred to as ‘slots’).
> 
> For example, these layers can store: raw counts (layer='counts'), normalized data (layer='data'), or z-scored/variance-stabilized data (layer='scale.data').
> 
> Data can be accessed using the $ accessor (i.e. obj[["RNA"]]$counts), or the `LayerData function (i.e. LayerData(obj, assay="RNA", layer='counts').
> 
> We’ve designed these updates to minimize changes for users. Existing Seurat functions and workflows from v4 continue to work in v5. For example, the command GetAssayData(obj, assay="RNA", slot='counts'), will run successfully in both Seurat v4 and Seurat v5.

A lot of function are using `obj[[assay]][slot]`, which is no longer supported. You can modify your function by changing them to one of `obj[[assay]]$slot` , `LayerData(obj, assay,slot)` or `GetAssayData(obj, assay, slot)`.

**Comment by 256wangliu** [comment]
same error
