### ISSUE TITLE
How to subset Xenium/ spatial object by cells and keep only molecules within these cells?

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#9085]
When I subset a Xenium object, the molecules of the parent object are not touched. I'm not sure if this is the expected behavior but I was wandering if the was a way to keep only the molecules within the cells of the smaller object.
```
> subset_xenium =subset(xenium.obj, cells=cells2keep)
> dim(xenium.obj@assays$Xenium$counts)
[1]    389 549534
> dim(subset_xenium@assays$Xenium$counts)
[1]   389 80364
> dim(xenium.obj@images$fov$molecules$ACE2@coords)
[1] 7697    2
> dim(subset_xenium@images$fov$molecules$ACE2@coords)
[1] 7697    2
```
Thanks!

**Comment by alikhuseynov** [comment]
This is actually for `SeuratObject`, there have been some updates but I'm not sure if `subset` now removes molecules that are not within the selected `cells` (ie, your `cells2keep`)
Sometime ago I implemented [`subset_opt`](https://github.com/alikhuseynov/add-on_R/blob/develop/R/subset_obj_seurat_v2.R) to also subset molecules. 
See this threads:
- https://github.com/satijalab/seurat/issues/6409#issuecomment-1315549535
- https://github.com/satijalab/seurat/issues/6409#issuecomment-2102985338

**Comment by rajuvee** [comment]
Did you every find an answer to this? The subset_opt function (including rev2) does not seem to solve my problems (see below):
<img width="787" alt="image" src="https://github.com/user-attachments/assets/8562a3a0-3da5-4ebc-92d8-b234a589e10c">

**Comment by alikhuseynov** [comment]
> Did you every find an answer to this? The subset_opt function (including rev2) does not seem to solve my problems (see below): 

first of all, please provide your run code. `subset_opt` will only remove provided cells or cluster category similar to `subset` itself. If you want to crop out those red cells then use `Crop` function or check this discussion: 

- https://github.com/satijalab/seurat/issues/8457 
- https://github.com/satijalab/seurat/issues/8457#issuecomment-1939594771

hope this helps

**Comment by alikhuseynov** [comment]
ok, my function is only a temporary solution and I haven't experimented much with `idents` arg. I think Seurat devs will soon add such support. 
Now, in Seurat the `molecules` slot is only used for visualization, no analysis is done on mols unless you want to use other R spatial packages or similar.
You can try to use `cells` arg to pass the cell ids that belong to "B_Plasma_0", and `features` arg to pass a character vector of genes you want to keep (eg, genes for "B_Plasma_0" cluster).

**Comment by kaizen89** [comment]
I was only trying to visualize the `molecules` on the subsetted object. 
```
xenium_sub = subset_opt(xenium.obj, cells = Cells(xenium_sub_v2), features = rownames(xenium_sub_v2)[1:5])
```
I do manage to subset the molecules this way but they still fall outside of cells used for subsetting, making the visualization not really intuitive.

**Comment by rajuvee** [comment]
As you can see my from image, the cells are subsetting appropriately and when I look inside the assay I believe they are subsetting appropriately as well. I think the only problem is in the FOV molecules slot where that does not work well at all. The problem being that crop is based on coordinates rather than cells which does not help. I have looked through your code base and it is very helpful but I am not seeing how it would apply to this problem?

**Comment by alikhuseynov** [comment]
the code can be optimized if one knows which molecules belong to which cells and uses that info to subset mols as well.

**Comment by xiangmingcai** [comment]
Hi all,
I managed to subset the molecules. However, this approach only works when you can draw a plygon to gate the subsets you need. 

```
library(GateData)

#define area with GateData
df = obj@meta.data
df$gate0 = TRUE
df_sampled = sample_n(df, 10000) 
##here I manually gate the area contains the subset cell population 
gate1<-PolygonGating(df=df_sampled, x_col= "x", y_col= "y", feature_col= "x",
                     parentgate_col= "gate0", newgate_col= "gate1",
                     canvas_width=800, canvas_height=400,
                     title_text = "TiTlE",subtitle_text = "SuBtItLe")
df <-GateDecider(gate = gate1, df = df)
obj$gate1 = df$gate1

# subset boundaries with subset_opt
obj_sub <- subset_opt(obj,subset = gate1)

# subset molecules with gate made
fov_sub = obj@images$fov
for (gene in names(fov_sub@molecules$molecules)) {
  sp_obj = fov_sub$molecules[[gene]]
  tmp_df = as.data.frame(sp_obj@coords)
  tmp_df$gate0 = TRUE
  tmp_df <-GateDecider(gate = gate1, df = tmp_df)
  keep_idx <- rownames(tmp_df)[tmp_df$gate1]
  sp_obj_sub <- sp_obj[keep_idx, ]
  fov_sub@molecules$molecules[[gene]] <- sp_obj_sub
}
obj_sub@images$fov@molecules = fov_sub@molecules

```

<img width="1859" height="761" alt="Image" src="https://github.com/user-attachments/assets/22b19368-57e1-4e13-9546-9075df93e754" />
