### ISSUE TITLE
Warning to PrepSCTFindMarkers when I already have

### ISSUE THREAD

**Issue by yesitsjess** [satijalab/seurat#9130]
Hi, trying to run `FindAllMarkers` on SCT transformed data:
```
# find markers for each cluster
seu <- PrepSCTFindMarkers(seu, assay="SCT_Scaled_Centered")
seu <- SetIdent(seu, value="SNN_PCA_SCT_Scaled_Centered_res0.1")
all_markers <- FindAllMarkers(seu, assay="SCT_Scaled_Centered",
                              logfc.threshold=0.1,
                              test.use="wilcox",
                              min.pct=0.01,
                              min.cells.feature=3,
                              min.cells.group=3,
                              return.thresh=0.01,
                              recorrect.umi=F)
```

```
Warning: The following tests were not performed: 
Warning: When testing harmony3 versus all:
	Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`.
```

I've already run `PrepSCTFindMarkers` and I also added `recorrect.umi=F` just in case this counted as "subsetting" but it hasn't helped.

Any advice please?

**Comment by igrabski** [comment]
Hi, can you please show all the code in creating and processing this object up to this point?

**Comment by satkinson0115** [comment]
I'm running into the same problem, it's not registering that PrepSCTFindMarkers has been run.

Here is the code I ran:
```
merge_uninfect <- merge(uninfect_227, uninfect_63)
merge_infect <- merge(infect_48555, infect_602)
merge_all <- merge(uninfect_63, list(uninfect_227, infect_48555, infect_602), 
                   add.cell.ids = c("uninfect1","uninfect2","infected1","infected2"))
head(merge_all@meta.data)

merge_all <- SCTransform(merge_all, assay = "Spatial", verbose = TRUE)
merge_all  <- RunPCA(merge_all , assay = "SCT", verbose = FALSE)
merge_all  <- FindNeighbors(merge_all, reduction = "pca", dims = 1:30)
merge_all <- FindClusters(merge_all, verbose = FALSE)
merge_all  <- RunUMAP(merge_all, reduction = "pca", dims = 1:30)

##Add prediction label to metadata (from a separate integration)
head(meta_new_int_trim)
head(merge_all)
merge_all <- AddMetaData(merge_all, meta_new_int_trim)
head(merge_all@meta.data)

##Run PrepSCTFindMarkers
merge_all_prep <- PrepSCTFindMarkers(merge_all, assay = "SCT", verbose = TRUE)
```

The above step gave me the "Multiple UMI assays are used for SCTransform: Spatial, RNA" so I followed issue #8235 and changed the names to spatial:

```
SCTResults(merge_all, slot = "umi.assay")
slot(object = merge_all@assays$SCT@SCTModel.list[[2]], name = "umi.assay") <- "Spatial"
slot(object = merge_all@assays$SCT@SCTModel.list[[3]], name = "umi.assay") <- "Spatial"
slot(object = merge_all@assays$SCT@SCTModel.list[[4]], name = "umi.assay") <- "Spatial"
SCTResults(merge_all, slot = "umi.assay") #check that names are proper again
```
I was then able to successfully run PrepSCTFindMarkers, but FindMarkers does not work:
```
merge_all_prep <- PrepSCTFindMarkers(merge_all, assay = "SCT", verbose = TRUE)

##Run differential expression test - infected vs uninfected
de_markers_stromal2 <- FindMarkers(merge_all_prep, ident.1 = "infected", 
                                   group.by = "infection_state",
                            subset.ident = "2:Stromal-2")
```
FindMarkers gives me the same error about running PrePSCTFindMarkers:
```
Error in FindMarkers.SCTAssay(object = data.use, latent.vars = latent.vars,  : 
  Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`.
In addition: There were 36 warnings (use warnings() to see them)
```
In case it's helpful, here are the other 36 warnings from warnings():
Warning messages:
```
1: Not validating Centroids objects
2: Not validating Centroids objects
3: Not validating FOV objects
4: Not validating FOV objects
5: Not validating FOV objects
6: Not validating FOV objects
7: Not validating FOV objects
8: Not validating FOV objects
9: Not validating Seurat objects
10: Not validating Centroids objects
11: Not validating Centroids objects
12: Not validating FOV objects
13: Not validating FOV objects
14: Not validating FOV objects
15: Not validating FOV objects
16: Not validating FOV objects
17: Not validating FOV objects
18: Not validating Seurat objects
19: Not validating Centroids objects
20: Not validating Centroids objects
21: Not validating FOV objects
22: Not validating FOV objects
23: Not validating FOV objects
24: Not validating FOV objects
25: Not validating FOV objects
26: Not validating FOV objects
27: Not validating Seurat objects
28: Not validating Centroids objects
29: Not validating Centroids objects
30: Not validating FOV objects
31: Not validating FOV objects
32: Not validating FOV objects
33: Not validating FOV objects
34: Not validating FOV objects
35: Not validating FOV objects
36: Not validating Seurat objects
```
I also tried setting all the umi.assay names to RNA and reran PrepSCTFindMarkers, but still got the same error for FindMarkers. 
Any help would be greatly appreciated!

Thanks,
Samantha

Session info if needed:
```
> sessionInfo()
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.5.1      hdf5r_1.3.10       patchwork_1.2.0    Seurat_5.1.0      
[5] SeuratObject_5.0.2 sp_2.1-4           dplyr_1.1.4       

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3     rstudioapi_0.16.0      jsonlite_1.8.8        
  [4] magrittr_2.0.3         spatstat.utils_3.0-5   farver_2.1.2          
  [7] fs_1.6.4               vctrs_0.6.5            ROCR_1.0-11           
 [10] memoise_2.0.1          spatstat.explore_3.2-7 htmltools_0.5.8.1     
 [13] usethis_2.2.3          sctransform_0.4.1      parallelly_1.37.1     
 [16] KernSmooth_2.23-24     htmlwidgets_1.6.4      ica_1.0-3             
 [19] plyr_1.8.9             plotly_4.10.4          zoo_1.8-12            
 [22] cachem_1.1.0           igraph_2.0.3           mime_0.12             
 [25] lifecycle_1.0.4        pkgconfig_2.0.3        Matrix_1.7-0          
 [28] R6_2.5.1               fastmap_1.2.0          fitdistrplus_1.1-11   
 [31] future_1.33.2          shiny_1.8.1.1          digest_0.6.36         
 [34] colorspace_2.1-0       tensor_1.5             loupeR_1.1.1          
 [37] RSpectra_0.16-1        irlba_2.3.5.1          pkgload_1.4.0         
 [40] labeling_0.4.3         progressr_0.14.0       fansi_1.0.6           
 [43] spatstat.sparse_3.1-0  httr_1.4.7             polyclip_1.10-6       
 [46] abind_1.4-5            compiler_4.4.1         remotes_2.5.0         
 [49] withr_3.0.1            bit64_4.0.5            viridis_0.6.5         
 [52] fastDummies_1.7.3      pkgbuild_1.4.4         MASS_7.3-60.2         
 [55] sessioninfo_1.2.2      tools_4.4.1            lmtest_0.9-40         
 [58] httpuv_1.6.15          future.apply_1.11.2    goftest_1.2-3         
 [61] glue_1.7.0             nlme_3.1-164           promises_1.3.0        
 [64] grid_4.4.1             Rtsne_0.17             cluster_2.1.6         
 [67] reshape2_1.4.4         generics_0.1.3         gtable_0.3.5          
 [70] spatstat.data_3.1-2    tidyr_1.3.1            data.table_1.15.4     
 [73] utf8_1.2.4             spatstat.geom_3.2-9    RcppAnnoy_0.0.22      
 [76] ggrepel_0.9.5          RANN_2.6.1             pillar_1.9.0          
 [79] stringr_1.5.1          spam_2.10-0            RcppHNSW_0.6.0        
 [82] later_1.3.2            splines_4.4.1          lattice_0.22-6        
 [85] survival_3.6-4         bit_4.0.5              deldir_2.0-4          
 [88] tidyselect_1.2.1       miniUI_0.1.1.1         pbapply_1.7-2         
 [91] gridExtra_2.3          scattermore_1.2        devtools_2.4.5        
 [94] matrixStats_1.3.0      stringi_1.8.4          lazyeval_0.2.2        
 [97] codetools_0.2-20       tibble_3.2.1           BiocManager_1.30.23   
[100] cli_3.6.3              uwot_0.2.2             xtable_1.8-4          
[103] reticulate_1.38.0      munsell_0.5.1          Rcpp_1.0.12           
[106] globals_0.16.3         spatstat.random_3.2-3  png_0.1-8             
[109] parallel_4.4.1         ellipsis_0.3.2         dotCall64_1.1-1       
[112] profvis_0.3.8          urlchecker_1.0.1       listenv_0.9.1         
[115] viridisLite_0.4.2      scales_1.3.0           ggridges_0.5.6        
[118] leiden_0.4.3.1         purrr_1.0.2            rlang_1.1.4           
[121] cowplot_1.1.3 
```

**Comment by hchintalapudi** [comment]
I have the same issue where the error appears in one subsetted object but not others.
Any solution would be greatly appreciated.

Thanks.

**Comment by whytece** [comment]
Hi, I'm having the exact same issue as you both @satkinson0115 @yesitsjess , did you end up finding a solution? Thanks

**Comment by antsmer** [comment]
Hi, I'm also having the same issue. Did anyone end up finding a solution? 

Here is the code I used: 
```# setup libraries + parallel processing ####
# Load necessary packages quietly
suppressMessages({
  library(dplyr)
  library(Seurat)
  library(sctransform)
  library(clustree)
  library(hdf5r)
  library(ggplot2)
  library(SeuratDisk)
  library(SeuratObject)
  library(future)
  library(Matrix)
  library(yaml)
  library(patchwork)
  library(scater)
  library(scDblFinder)
  library(BiocParallel)
  library(ggsci)
  library(SingleCellExperiment) 
  #the following libraries help with seurat -> anndata conversion 
  library(sceasy)
  library(reticulate)
  reticulate::use_condaenv("wscrna_py38", required = TRUE)
  loompy <- reticulate::import('loompy')
  library(scCustomize)
})
# Set parallel processing for speed
plan(multisession, workers = 3)
# set seed for reproducibility 
set.seed(100)

# naive_b1 ####
## Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/additional_seq_for_batch_1_3_6/cellbender/Naive_B1/Naive_B1_filtered.h5', mode = 'r')
adata <- readRDS('allcells.rds')# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
naive_b1 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'naive_b1'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(naive_b1))
sample.info$sampleID <- 'naive'   # Put actual library/sample name here
sample.info$batch <- 'batch_1'       # Set your batch label
## Assign metadata ####
naive_b1[['sampleID']] <- sample.info$sampleID
naive_b1[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(naive_b1) <- 'sampleID'
# Inspect number of features/cells pre-QC
naive_b1@assays  # TODO: List the number of features and genes (e.g. '24887 features for 8775 cells')

# cci_mid_b3 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/additional_seq_for_batch_1_3_6/cellbender/CCI_Mid_B3/CCI_Mid_B3_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
cci_mid_b3 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'cci_mid_b3'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(cci_mid_b3))
sample.info$sampleID <- 'cci_mid'   # Put actual library/sample name here
sample.info$batch <- 'batch_3'       # Set your batch label
## Assign metadata ####
cci_mid_b3[['sampleID']] <- sample.info$sampleID
cci_mid_b3[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(cci_mid_b3) <- 'sampleID'
# Inspect number of features/cells pre-QC
cci_mid_b3@assays  # TODO: List the number of features and genes (e.g. '26130 features for 10141 cells')

# cci_chronic_b3 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/additional_seq_for_batch_1_3_6/cellbender/CCI_Chronic_B3/CCI_Chronic_B3_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
cci_chronic_b3 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'cci_chronic_b3'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(cci_chronic_b3))
sample.info$sampleID <- 'cci_chronic'   # Put actual library/sample name here
sample.info$batch <- 'batch_3'       # Set your batch label
## Assign metadata ####
cci_chronic_b3[['sampleID']] <- sample.info$sampleID
cci_chronic_b3[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(cci_chronic_b3) <- 'sampleID'
# Inspect number of features/cells pre-QC
cci_chronic_b3@assays  # TODO: List the number of features and genes (e.g. '24884 features for 6051 cells')

# sni_mid_b3 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/batch_3/cellbender/sni_mid/sni_mid_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
sni_mid_b3 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'sni_mid_b3'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(sni_mid_b3))
sample.info$sampleID <- 'sni_mid'   # Put actual library/sample name here
sample.info$batch <- 'batch_3'       # Set your batch label
## Assign metadata ####
sni_mid_b3[['sampleID']] <- sample.info$sampleID
sni_mid_b3[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(sni_mid_b3) <- 'sampleID'
# Inspect number of features/cells pre-QC
sni_mid_b3@assays  # TODO: List the number of features and genes (e.g. '25429 features for 6714 cells')

# sni_chronic_b3 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/batch_3/cellbender/sni_chronic/sni_chronic_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
sni_chronic_b3 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'sni_chronic_b3'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(sni_chronic_b3))
sample.info$sampleID <- 'sni_chronic'   # Put actual library/sample name here
sample.info$batch <- 'batch_3'       # Set your batch label
## Assign metadata ####
sni_chronic_b3[['sampleID']] <- sample.info$sampleID
sni_chronic_b3[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(sni_chronic_b3) <- 'sampleID'
# Inspect number of features/cells pre-QC
sni_chronic_b3@assays  # TODO: List the number of features and genes (e.g. '25270 features for 8145 cells')

# cci_acute_b6 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/batch_6/cellbender/cci_acute/cci_acute_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
cci_acute_b6 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'cci_acute_b6'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(cci_acute_b6))
sample.info$sampleID <- 'cci_acute'   # Put actual library/sample name here
sample.info$batch <- 'batch_6'       # Set your batch label
## Assign metadata ####
cci_acute_b6[['sampleID']] <- sample.info$sampleID
cci_acute_b6[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(cci_acute_b6) <- 'sampleID'
# Inspect number of features/cells pre-QC
cci_acute_b6@assays  # TODO: List the number of features and genes (e.g. '24126 features for 6906 cells')

# sni_acute_b6 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/additional_seq_for_batch_1_3_6/cellbender/SNI_Acute_B6/SNI_Acute_B6_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
sni_acute_b6 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'sni_acute_b6'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(sni_acute_b6))
sample.info$sampleID <- 'sni_acute'   # Put actual library/sample name here
sample.info$batch <- 'batch_6'       # Set your batch label
## Assign metadata ####
sni_acute_b6[['sampleID']] <- sample.info$sampleID
sni_acute_b6[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(sni_acute_b6) <- 'sampleID'
# Inspect number of features/cells pre-QC
sni_acute_b6@assays  # TODO: List the number of features and genes (e.g. '26317 features for 21782 cells')

# cci_chronic_b6 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/additional_seq_for_batch_1_3_6/cellbender/CCI_Chronic_B6/CCI_Chronic_B6_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
cci_chronic_b6 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'cci_chronic_b6'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(cci_chronic_b6))
sample.info$sampleID <- 'cci_chronic'   # Put actual library/sample name here
sample.info$batch <- 'batch_6'       # Set your batch label
## Assign metadata ####
cci_chronic_b6[['sampleID']] <- sample.info$sampleID
cci_chronic_b6[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(cci_chronic_b6) <- 'sampleID'
# Inspect number of features/cells pre-QC
cci_chronic_b6@assays  # TODO: List the number of features and genes (e.g. '23965 features for 8004 cells')

# naive_b6 ####
## ---------- Load Single Library ####
# Fix for read10XH5 issue: https://github.com/satijalab/seurat/issues/732
h5_data <- H5File$new('F:/internal_datasets/rd_dpp/batch_6/cellbender/naive/naive_filtered.h5', mode = 'r')
# Create sparse matrix from HDF5 dataset
feature_matrix <- Matrix::sparseMatrix(
  i = h5_data[['matrix/indices']][],
  p = h5_data[['matrix/indptr']][],
  x = h5_data[['matrix/data']][],
  dimnames = list(
    h5_data[['matrix/features/name']][],
    h5_data[['matrix/barcodes']][]
  ),
  dims = h5_data[['matrix/shape']][],
  index1 = FALSE
)
# Close HDF5 file
h5_data$close_all()
# Ensure row names (gene names) are unique
rownames(feature_matrix) <- make.unique(rownames(feature_matrix))
# Create Seurat object: genes in at least 3 cells, cells with >= 200 genes
naive_b6 <- CreateSeuratObject(
  counts = feature_matrix,
  min.cells = 3,
  min.features = 200,
  project = 'naive_b6'
)
# Assign sample identity to cells
sample.info <- data.frame(cell.names = colnames(naive_b6))
sample.info$sampleID <- 'naive'   # Put actual library/sample name here
sample.info$batch <- 'batch_6'       # Set your batch label
## Assign metadata ####
naive_b6[['sampleID']] <- sample.info$sampleID
naive_b6[['batch']] <- sample.info$batch
# Set identity to sampleID
Idents(naive_b6) <- 'sampleID'
# Inspect number of features/cells pre-QC
naive_b6@assays  # TODO: List the number of features and genes (e.g. 23723 features for 6352 cells')

# ---------- merge all libraries ####
adata <- merge(x = naive_b1, y = c(cci_mid_b3, cci_chronic_b3, sni_mid_b3, sni_chronic_b3, cci_acute_b6, sni_acute_b6, cci_chronic_b6, naive_b6)) 
# Join all the layers (samples) together
adata[["RNA"]] <- JoinLayers(adata[["RNA"]])
# make another metadata column with both sample and batch: 
adata$sample_batch <- factor(paste(adata$sampleID, adata$batch, sep = "_"))
# Check gene and cell counts after merge
adata@assays #TODO: list the number of genes and feature here: 27653 features for 82870 cells
# Create merged mito % column 
adata[['percent.mito']] <- PercentageFeatureSet(adata, pattern = '^mt-')

# Save the merged object so you don't have to rerun the whole code if R crashes
saveRDS(adata, 'F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files/merged.rds')

# Map quality control threshold values before you do doublet removal ####
qc <- adata@meta.data  
qc$umi_outlier  <- isOutlier(qc$nCount_RNA,   nmads = 5, type = "both")
qc$feature_outlier  <- isOutlier(qc$nFeature_RNA,   nmads = 5, type = "both")
qc$mito_outlier  <- isOutlier(qc$percent.mito,   nmads = 5, type = "both")
adata@meta.data <- qc

# ---------- Doublet removal #### 
# convert to a singlecellexperiment object as the input of scDblFinder is an object of class SingleCellExperiment (not seurat) where empty drops having already been removed and the object contains at least the counts (assay ‘counts’).
sce <- as.SingleCellExperiment(adata) # or if that doesnt work try sce <- as.SingleCellExperiment(adata)
#run doublet finder
bp <- SnowParam(workers = 3, RNGseed = 1234) # this ensure reproducibility
#Since both the cluster-based or not cluster based doublet identificaton approach of scDblFinder perform very similarly overall in benchmarks, I just went with the defult (which is the not cluster based approach).
sce <- scDblFinder(sce, samples = "batch", BPPARAM = bp) # you can also use dbr.per1k to set mutliplet rate but for standard 10X data, the 10X documentation indicates a doublet rate of roughly 0.8% per 1000 cells captured, which is the default value of dbr.per1k
# look at how many doublets you have and see if it makes sense 
table(sce$scDblFinder.class) # singlet 68335 doublet 14535
# Convert colData to a data.frame
meta_scdblfinder <- as.data.frame(sce@colData@listData)
# Keep only the scDblFinder-related columns
meta_scdblfinder <- dplyr::select(meta_scdblfinder, starts_with("scDblFinder"))
# Check first few rows
head(meta_scdblfinder)
# Make sure rownames are aligned with cells
rownames(meta_scdblfinder) <- sce@colData@rownames
# Check again
head(meta_scdblfinder)
# Add all scDblFinder columns to your Seurat object
adata <- AddMetaData(object = adata, metadata = meta_scdblfinder)
# plot it to make sure it makes sense and save the plot   
pdf_file <- file.path('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/figures/r_generated', "doubet.pdf") 
# Open the PDF device
pdf(pdf_file, width = 11, height = 6)
VlnPlot(adata, group.by = 'sampleID', split.by = "scDblFinder.class",
        features = c("nFeature_RNA", "nCount_RNA", "percent.mito"), pt.size = 0) + 
  theme(legend.position = 'right')
dev.off()
# If it doesn't look right, go back and manually set thresholds yourself (based on the plot, I think it looks pretty good with a doublet rate of ~17.5% so I went ahead here)
# subset only the singlet cells (remove the doublets)
adata <- subset(adata, subset = scDblFinder.class == 'singlet')
adata@assays # number of cells after doublet removal: 27653 features across 68335 cells

# ---------- Further quality control ####
# this was shifted to after doublet removal for two reasons: 1. the default expected doublet rate is calculated on the basis of the cells given, and if you excluded a lot of cells as low quality, scDblFinder might think that the doublet rate should be lower than it is.
# first plot it to see how it looks
pdf_file <- file.path('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/figures/r_generated', "qcmetrics.pdf")
# Open the PDF device
pdf(pdf_file, width = 11, height = 11)
ggplot(adata@meta.data, aes(x = nCount_RNA, y = percent.mito, color = umi_outlier | feature_outlier | mito_outlier)) +
  geom_point(alpha = 0.6, size = 1) +
  facet_wrap(~sampleID, scales = "free") +
  scale_color_manual(values = c("FALSE" = "black", "TRUE" = "red")) +
  labs(title = "% mito vs nCount_RNA",
       x = "nCount_RNA (UMIs)",
       y = "% Mitochondrial",
       color = "Outlier") +
  theme_minimal()
ggplot(adata@meta.data, aes(x = nCount_RNA, y = nFeature_RNA, color = umi_outlier | feature_outlier | mito_outlier)) +
  geom_point(alpha = 0.6, size = 1) +
  facet_wrap(~sampleID, scales = "free") +
  scale_color_manual(values = c("FALSE" = "black", "TRUE" = "red")) +
  labs(title = "nCount_RNA vs nFeature_RNA",
       x = "nCount_RNA (UMIs)",
       y = "nFeature_RNA (genes)",
       color = "Outlier") +
  theme_minimal()
dev.off()
#after confirm it looks good then proceed to remove the outliers
cells_to_keep <- rownames(qc)[!(qc$umi_outlier | qc$feature_outlier | qc$mito_outlier)]
adata <- subset(adata, cells = cells_to_keep)
adata@assays # number of cells after removal of dead cells: 27653 features for 59037 cells

# ---------- SCT ####
# increase memory usage limits so you are not hit with an error
options(future.globals.maxSize = 18700 * 1024^2)  # increase max.size memory limit if needed
# Switch to sequential processing so you are not hit with an error
plan(future::sequential)
# Split by batch. In doing do, normalization and variable feature identification is performed for each batch independently (a consensus set of variable features is automatically identified).
adata[["RNA"]] <- split(adata[["RNA"]], f = adata$batch)
# Check that its split by batch 
adata[["RNA"]]
# Normalize, scale, and find variable features using sct (this is better for removing confounds by technical factors including sequencing depth)
adata <- SCTransform(adata, vars.to.regress = c('nCount_RNA', 'nFeature_RNA', 'percent.mito'), vst.flavor = 'v2', return.only.var.genes = FALSE) # set return.only.var.genes to false to scale all genes
# PCA
adata <- RunPCA(adata, verbose = FALSE)
# Switch to parallel processing for speed
plan(multisession, workers = 3)
# Elbow plot to choose number of PCs
ElbowPlot(adata, ndims = 50) # ndims = 50 is only visual; downstream dims_to_use is what's used.
# Choose the number of dims/PCs
dims_to_use <- 23 #TODO: Set this as your number of PCs/dims (e.g., 20) based on the ElbowPlot
# Find neighbors using PCs (set dims to chosen number after elbow plot inspection)
adata <- FindNeighbors(adata, dims = 1:dims_to_use, verbose = FALSE)

# ---------- Clustering ####
# Use sequential processing for reproducibility
plan(future::sequential)
set.seed(1234)
# Cluster across resolutions 
resolutions <- seq(0.0, 0.1, by = 0.02)
for (res in resolutions) {
  adata <- FindClusters(adata, verbose = FALSE, resolution = res, cluster.name = paste0("merged_res_", res))
  adata <- RunUMAP(adata, dims = 1:dims_to_use, verbose = FALSE, n.neighbors = 30, min.dist = 0.3, reduction.name = "umap.merged")
}
# Visualize cluster tree to decide optimal resolution
clustree(adata, prefix = "merged_res_")
final_res <- 0.04 # TODO: Set your resolution here 
# Rerun FindClusters and RunUMAP with the chosen resolution
adata <- FindClusters(adata, verbose = FALSE, resolution = final_res, cluster.name = paste0("merged_res_", final_res))
adata <- RunUMAP(adata, dims = 1:dims_to_use, verbose = FALSE, n.neighbors = 30, min.dist = 0.3, reduction.name = "umap.merged")

# ---------- Plot clusters ####
# first make sure your clusters look good in terms of quality control 
plot1 <- FeatureScatter(adata, feature1 = 'nCount_RNA', feature2 = 'percent.mito')
plot2 <- FeatureScatter(adata, feature1 = 'nCount_RNA', feature2 = 'nFeature_RNA')
wrap_plots(plots = list(plot1, plot2))
VlnPlot(adata, features = "percent.mito", group.by = "seurat_clusters", pt.size = 0.1) +
  ggtitle("Percent Mitochondrial Content by Cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # they did look good to me so i moved on 
# now define you color scheme
my_colors <- pal_d3("category20")(20)
# Now actually plot your clusters
pdf_file <- file.path('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/figures/r_generated', "merged_umaps.pdf") 
# Start PDF Device
pdf(pdf_file, height = 15, width = 45)
DimPlot(adata, reduction = "umap.merged", group.by = c('sampleID', 'batch', 'sample_batch', paste0("merged_res_", final_res)), combine = FALSE, cols = my_colors, raster = FALSE)
DimPlot(adata, reduction = "umap.merged", group.by = c('sample_batch'), split.by = c('sampleID'), combine = FALSE, cols = my_colors, raster = FALSE)
DimPlot(adata, reduction = 'umap.merged', label = TRUE, group.by = c(paste0("merged_res_", final_res), 'sampleID', 'batch', 'sample_batch'), cols = my_colors, raster = FALSE) # The group.by argument colors the umap accordingly; for example, by cluster ID and sample ID
DimPlot(adata, reduction = 'umap.merged', label = TRUE, group.by = c('sampleID'), split.by = c('sample_batch'), cols = my_colors, raster = FALSE) 
dev.off()
# Save the merged object 
saveRDS(adata, 'F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files/merged_completed.rds')

# Integration ####
# Note: the last time I tried the integrated fastmnn method I got the following error 'Error in get(x = method) : object 'FastMNNIntegration'' not found so did not run this intgeration analysis here. 

# convert to a v5 assay. It is a V5 assay but this is just for safety
adata[["RNA"]] <- as(adata[["RNA"]], Class = "Assay5")
# Join all the layers together
adata[["RNA"]] <- JoinLayers(adata[["RNA"]])
# Split by batch instead so integration works between batches rather than samples/libraries
adata[["RNA"]] <- split(adata[["RNA"]], f = adata$batch)
# Check that its split by batch 
adata[["RNA"]]
# Switch to sequential processing so you are not hit with an error and r does not crash
plan(sequential)

## integrate rpca method ####
adata <- IntegrateLayers(object = adata, method = RPCAIntegration, normalization.method = "SCT", new.reduction = "integrated.rpca", verbose = FALSE)
adata <- FindNeighbors(adata, reduction = "integrated.rpca", dims = 1:dims_to_use)
adata <- FindClusters(adata, resolution = final_res, cluster.name = "rpca_clusters")
adata <- RunUMAP(adata, reduction = "integrated.rpca", dims = 1:dims_to_use, reduction.name = "umap.rpca")
pdf_file <- file.path('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/figures', "rpca_umap.pdf") 
pdf(pdf_file, height = 15, width = 50)
DimPlot(adata, reduction = "umap.rpca", group.by = c('sampleID', 'batch', 'sample_batch', "rpca_clusters"), combine = FALSE, cols = my_colors, raster = FALSE)
DimPlot(adata, reduction = "umap.rpca", group.by = c('sample_batch'), split.by = c('sampleID'), combine = FALSE, cols = my_colors, raster = FALSE)
dev.off()

## integrated harmony method ####
adata <- IntegrateLayers(object = adata, method = HarmonyIntegration, normalization.method = "SCT", new.reduction = "integrated.harmony", verbose = FALSE)
adata <- FindNeighbors(adata, reduction = "integrated.harmony", dims = 1:dims_to_use)
adata <- FindClusters(adata, resolution = final_res, cluster.name = "harmony_clusters")
adata <- RunUMAP(adata, reduction = "integrated.harmony", dims = 1:dims_to_use, reduction.name = "umap.harmony")
pdf_file <- file.path('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/figures', "harmony_umap.pdf")
pdf(pdf_file, height = 15, width = 50)
DimPlot(adata, reduction = "umap.harmony", group.by = c('sampleID', 'batch', 'sample_batch', "harmony_clusters"), combine = FALSE, cols = my_colors, raster = FALSE)
DimPlot(adata, reduction = "umap.harmony", group.by = c('sample_batch'), split.by = c('sampleID'), combine = FALSE, cols = my_colors, raster = FALSE)
dev.off()

## integrated cca method #### 
adata <- IntegrateLayers(object = adata, method = CCAIntegration, normalization.method = "SCT", new.reduction = "integrated.cca", verbose = FALSE)
adata <- FindNeighbors(adata, reduction = "integrated.cca", dims = 1:dims_to_use)
adata <- FindClusters(adata, resolution = final_res, cluster.name = "cca_clusters")
adata <- RunUMAP(adata, reduction = "integrated.cca", dims = 1:dims_to_use, reduction.name = "umap.cca")
pdf_file <- file.path('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/figures', "cca_umap.pdf") 
pdf(pdf_file, height = 15, width = 50)
DimPlot(adata, reduction = "umap.cca", group.by = c('sampleID', 'batch', 'sample_batch', "cca_clusters"), combine = FALSE, cols = my_colors, raster = FALSE)
DimPlot(adata, reduction = "umap.cca", group.by = c('sample_batch'), split.by = c('sampleID'), combine = FALSE, cols = my_colors, raster = FALSE)
dev.off()

# ---------- Clustering after integration ####
# now, review your different umaps from the different integration and pick one
# CCA integration looks best so thats why it was chosen. It matches the 2 naive samples from the different batches (both batch 1 and 6 naive are C57bl6) animals the best. The CCI chronic animals aren't matched that great but this is the case with all of the integration methods. This could be because of the different ages that they were collected or the difference in genotype/tamoxifen treatment or how many weeks post injury they were collected (batch 3 CCI chronic was CCR2 Ai9 treated with tamoxifen, euthanized at 16 weeks post injury at 8.5 months of age; batch 6 CCI chronic was C57bl6, euthanized at 11 weeks post injury at 5.75 months of age; to note both 11 and 16 weeks were resolved from pain by the time they were collected). 
# Copy the content of 'umap.cca' into 'umap'and integrated.cca into pca
adata@reductions$pca <- adata@reductions$`integrated.cca`
adata@reductions$umap <- adata@reductions$`umap.cca`
# save the integrated object so you can refer to it if you need
saveRDS(adata, file = file.path(output_dir, 'allcells_integrated.rds'))
# delete all other dimetionality reductions so the only one thats used downstream is cca 
# List of reductions to keep
keep_reductions <- c("integrated.cca", "umap.cca", "umap", "pca")  
# Delete all other reductions
for (r in names(adata@reductions)) {
  if (!(r %in% keep_reductions)) {
    adata@reductions[[r]] <- NULL
  }
}
# cluster at various resolutions for the cca integration 
# Use sequential processing for reproducibility
plan(future::sequential)
set.seed(1234)
# Cluster across resolutions 
resolutions <- seq(0.0, 0.1, by = 0.01)
for (res in resolutions) {
  adata <- FindClusters(adata, verbose = FALSE, resolution = res, cluster.name = paste0("cca_res_", res))
  adata <- RunUMAP(adata, reduction = "integrated.cca", dims = 1:dims_to_use, verbose = FALSE, n.neighbors = 30, min.dist = 0.3, reduction.name = "umap.cca")
}
# Visualize cluster tree to decide optimal resolution
clustree(adata, prefix = 'cca_res_')
final_res <- 0.02 # TODO: Set your resolution here 
# Set chosen resolution
adata <- FindClusters(adata, verbose = FALSE, resolution = final_res, cluster.name = paste0("cca_res_", final_res))
adata <- RunUMAP(adata, dims = 1:dims_to_use, verbose = FALSE, n.neighbors = 30, min.dist = 0.3, reduction.name = "umap.cca") 
# note that after running this, i got the following message: Warning message: Key ‘umapcca_’ taken, using ‘maujg_’ instead. it renamed it from umapcca_ to maujg_ so thats what you will see in any umap plots you make (its because: colnames(Embeddings(adata[["umap.cca"]])) [1] "maujg_1" "maujg_2")
DimPlot(adata, reduction = "umap.cca", group.by = c('sampleID', 'batch', 'sample_batch', paste0("cca_res_", final_res)), combine = FALSE)
# this plot should show also the cca umap. if it does not there is an issue and you have to fix it before moving forward
DimPlot(adata, group.by = c('sample_batch'), combine = FALSE)

# ---------- Assign sex based on the expression of sex specific genes ####
# method 1: use both male and female specific genes 
# Male genes (these were taken from Sameera)
male_genes <- list(c("Ddx3y", "Eif2s3y","Gm29650", "Kdm5d", "Uty"))
adata <- AddModuleScore(adata, features = male_genes, name = 'Male_Cells')
# Female genes (these were taken from Sameera)
female_genes <- list(c("Xist"))
adata <- AddModuleScore(adata, features = female_genes, name = 'Female_Cells')
# visualize the scores 
VlnPlot(adata, features = c("Male_Cells1","Female_Cells1"), pt.size = 0.0)
FeaturePlot(adata, features = c("Male_Cells1","Female_Cells1"), reduction = umap_choice, combine = FALSE)
# Method 1: assign sex by setting threshold
# Calculate dynamic thresholds (50th percentile)
male_threshold <- quantile(adata$Male_Cells1, probs = 0.5, na.rm = TRUE)
female_threshold <- quantile(adata$Female_Cells1, probs = 0.5, na.rm = TRUE)
# Assign sex based on thresholds
adata$sex1 <- "unknown"
adata$sex2 <- "unknown"
adata$sex1[adata$Male_Cells1 > male_threshold] <- "male"
adata$sex2[adata$Female_Cells1 > female_threshold] <- "female"
# see how many cells are labelled as both male and female 
sum(adata$sex1 == "male" & adata$sex2 == "female")
# redefine those cells as unknown 
adata$sex1[adata$sex1 == "male" & adata$sex2 == "female"] <- "unknown"
adata$sex2[adata$sex1 == "male" & adata$sex2 == "female"] <- "unknown"
table(adata$sex1)
table(adata$sex2)
# Create a new column for combined sex classification
adata$sex <- "unknown"
# Assign 'male' if sex1 is male and sex2 is not female
adata$sex[adata$sex1 == "male"] <- "male"
# Assign 'female' if sex2 is female and sex1 is not male
adata$sex[adata$sex2 == "female"] <- "female"
table(adata$sex) # 29518 female, 16392 male, 13127 unknown 
# given that we expect 1/2 female cells and 1/2 male cells, it might be wise to merge 'uknown' with 'male' such that they are all labelled as male to get at this expected ratio. 

# ---------- Save Processed object ####
# Switch back to parallel for speed
plan(multisession, workers = 3)
# define output directory 
output_dir <- 'F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files'
# save the object with all its various demtionality reductions ####
# Save as RDS
saveRDS(adata, file = file.path(output_dir, 'allcells_cca_integrated.rds'))
# Save the object directly from seurat to anndata to avoid gene drop out
as.anndata(
  x = adata,
  file_path = "F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files",
  file_name = "allcells_cca_integrated.h5ad",
  assay = "SCT",                       # Make sure you're using the correct assay
  main_layer = "data",                 # Use normalized data as main layer
  other_layers = c("counts"),          # Also include raw counts
  transfer_norm.data = TRUE,           # Explicitly transfer norm.data layer
  transfer_dimreduc = TRUE,            # Include UMAP, PCA, etc.
  verbose = TRUE                       # Show progress
)
# Save the SCT highly variable features to a file
hvg_genes <- adata@assays[["SCT"]]@var.features
write.csv(hvg_genes, file = "F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files/sct_hvg.csv", row.names = FALSE)
# See and run sccaf script at this point 

## Read in your SCCAF data ####
# Go back and rerun 'Load Single Library' Lines of code 
# Load Seurat object
adata <- readRDS('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files/allcells_cca_integrated.rds')
# Load SCCAF metadata (clusters)
adata_SCCAF <- read.csv('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files/allcells_hvg_r0.01-0.03_cln.csv', header = FALSE, row.names = 1)
# Add SCCAF cluster info to Seurat object
adata[['SCCAF']] <- adata_SCCAF
# Set identity to SCCAF
Idents(adata) <- 'SCCAF'
# Plot SCCAF clusters
DimPlot(adata, reduction = 'umap', label = TRUE, raster = FALSE)
# Optional: plot colored by SCCAF + sample ID
DimPlot(adata, reduction = 'umap', label = TRUE, group.by = c('SCCAF', 'sampleID'), raster = FALSE)
# Save an updated object with the cluster names
saveRDS(adata, file = 'F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files/allcells_cca_integrated_cln.rds')
# ---------- Setup libraries + parallel processing ####
# Load necessary packages quietly
suppressMessages({
  library(Seurat)       # For scRNA-seq analysis
  library(openxlsx)     # For saving results to Excel
  library(yaml)         # For reading in config.yaml
  library(future)       # For parallel processing
})
# Set parallel processing for speed
plan(multisession, workers = 3)

# Read your RDS object 
adata <- readRDS('F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/data_files/allcells_cca_integrated_cln.rds')

#set output directory
output_dir <- 'F:/internal_datasets/da/batch1_3_6_w_additonal_seq/1)allcells/deg_go'

# ---- BEFORE ----
# Store median UMI counts before PrepSCTFindMarkers()
umi_before <- sapply(adata@assays$SCT@SCTModel.list, function(model) {
  model@median_umi
})
# Show median UMIs before
cat("Before PrepSCTFindMarkers():\n")
print(umi_before)
# batch_1 batch_3 batch_6 
# 3980    4106    2723 
# correct counts
PrepSCTFindMarkers(object = adata, assay = "SCT")
# ---- AFTER ----
# Store median UMI counts after PrepSCTFindMarkers()
umi_after <- sapply(adata@assays$SCT@SCTModel.list, function(model) {
  model@median_umi
})
# Show median UMIs after
cat("After PrepSCTFindMarkers():\n")
print(umi_after)
# batch_1 batch_3 batch_6 
# 3980    4106    2723 # you can see it didnt change anything 


# Calculate DEGs
adata.markers <- FindAllMarkers(
  object = adata, 
  only.pos = TRUE, # Change to FALSE if you want both up/down genes
  min.pct = 0.25, # the threshold is high here because I need genes that are upregulated in a large proportion of a cell type population so we can have appropriate gene markers that differentiate the various cell populations          
  logfc.threshold = 0.25, # the threshold is high here because I need genes that are upregulated in a large proportion of a cell type population so we can have appropriate gene markers that differentiate the various cell populations     
  slot = "data",
  recorrect.umi = FALSE,
  assay = "SCT"
) 
# I get the following error message: Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`. even after having run PrepSCTFindMarkers()```

Any help would be appreciated. Thank you so much!

**Comment by igrabski** [comment]
Hi, can you please check what version of Seurat you are using, and try with it updated if it's not the most recent version? We addressed some SCTransform-related problems in an earlier update, and it may resolve your issue.

**Comment by antsmer** [comment]
Thank you for the quick reply! I upgraded Seurat from 5.2.1 which is what I had used previously to 5.3.0 but I still get the same error. I also examined median UMI counts before and after I did PrepSCTFindMarkers and I get: 
```
# ---- BEFORE ----
# Store median UMI counts before PrepSCTFindMarkers()
umi_before <- sapply(adata@assays$SCT@SCTModel.list, function(model) {
  model@median_umi
})
# Show median UMIs before
cat("Before PrepSCTFindMarkers():\n")
print(umi_before)
# output is as follows: 
# batch_1 batch_3 batch_6 
# 3980    4106    2723 

# Now correct counts
PrepSCTFindMarkers(object = adata, assay = "SCT") 
# this runs without any errors, here is the output: 
#Found 3 SCT models. Recorrecting SCT counts using minimum median counts: 2723
#An object of class Seurat 
#52640 features across 59037 samples within 2 assays 
#Active assay: SCT (24987 features, 3000 variable features)
#3 layers present: counts, data, scale.data
#1 other assay present: RNA
#4 dimensional reductions calculated: pca, integrated.cca, umap.cca, umap

# ---- AFTER ----
# Store median UMI counts after PrepSCTFindMarkers()
umi_after <- sapply(adata@assays$SCT@SCTModel.list, function(model) {
  model@median_umi
})
# Show median UMIs after
cat("After PrepSCTFindMarkers():\n")
print(umi_after)
# output is as follows: 
# batch_1 batch_3 batch_6 
# 3980    4106    2723 # you can see it didnt change anything 
```
Any guidance would be appreciated!
Thank you in advance!

**Comment by BenjaminDEMAILLE** [comment]
Reproduced and fixed in https://github.com/satijalab/seurat/pull/10468.

**Cause.** `PrepSCTFindMarkers()` returns early when

```r
all(unlist(x = model_median_umis) > min_median_umi)
```

`min_median_umi` is the smallest median UMI observed across the models' cells, so the models sitting *above* it are exactly the ones whose counts are on the wrong scale. The early return therefore skips the objects that need recorrecting. `FindMarkers.SCTAssay()` requires the opposite (`median_umi == min(observed)`), so it then rejects the object it was being prepared for. The condition was `==` until d97a5f6f in Dec 2022.

**When you hit it.** Whenever cells are removed after `SCTransform`. The observed medians are recomputed from the cells that remain, while each model's stored `median_umi` keeps the depth from fit time, so dropping low-UMI cells from one sample can put every stored median above the new minimum. Minimal reproduction:

```
stored model medians       : 143, 230.5
observed medians after subset: 143, 106
Minimum UMI unchanged. Skipping re-correction.
FindMarkers -> ERROR: Object contains multiple models with unequal library sizes.
```

**Workaround until the fix lands**, forcing the recorrection by putting the stored medians back to what is observed:

```r
obs <- lapply(SCTResults(seu[["SCT"]], slot = "cell.attributes"),
              function(x) median(x[, "umi"]))
SCTResults(seu[["SCT"]], slot = "median_umi") <- obs
seu <- PrepSCTFindMarkers(seu)
```

Separately, @yesitsjess: `FindMarkers` spells that argument `recorrect_umi`, with an underscore. `recorrect.umi = FALSE` is swallowed by `...` and does nothing, which is why it did not help.

cc @igrabski @satkinson0115 @whytece

---
*Outside contribution: I am not a member of the Seurat dev team, and this comment is not an official answer from the maintainers.*
