### ISSUE TITLE
BUG: Error in `reference[["SCT"]]`: ! 'SCT' not found in this Seurat object

### ISSUE THREAD

**Issue by sameet** [satijalab/seurat#9864]
### Issue Description

I was trying to run `Azimuth` on a sample.  I was using the `mousecortexref` as my reference.

```
> sce
An object of class Seurat 
53556 features across 6160 samples within 2 assays 
Active assay: SCT (21271 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
```

### Reproducing Code Example

```R
sce <- RunAzimuth(sce, reference = "mousecortexref")

Warning: Overwriting miscellanous data for model
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
detected inputs from MOUSE with id type Gene.name
reference rownames detected MOUSE with id type Gene.name
Normalizing query using reference SCT model
Warning: No layers found matching search pattern provided
Warning: 65 features of the features specified were not present in both the reference query assays. 
Continuing with remaining 2935 features.
Error in `reference[["SCT"]]`:
! 'SCT' not found in this Seurat object
 
Run `rlang::last_trace()` to see where the error occurred.
```

### Error Message

```shell
Error in `reference[["SCT"]]`:
! 'SCT' not found in this Seurat object
 
Run `rlang::last_trace()` to see where the error occurred.


> rlang::last_trace()
<error/rlang_error>
Error in `reference[["SCT"]]`:
! 'SCT' not found in this Seurat object
 
---
Backtrace:
    ▆
 1. ├─Azimuth::RunAzimuth(sce, reference = "mousecortexref")
 2. └─Azimuth:::RunAzimuth.Seurat(sce, reference = "mousecortexref")
 3.   └─Seurat::FindTransferAnchors(...)
 4.     ├─reference[["SCT"]]
 5.     └─SeuratObject:::`[[.Seurat`(reference, "SCT")
Run rlang::last_trace(drop = FALSE) to see 5 hidden frames.
```

### Additional Comments

The `RunAzimuth` has always worked for me.  I recently upgraded my `R` to `4.5`, and `Seurat` to `5.3`.  This very data-set has also been processed before with version `5.2` of `Seurat`.

### Session Info

```shell
> sessionInfo()
R version 4.5.0 (2025-04-11)
Platform: aarch64-apple-darwin20
Running under: macOS Sequoia 15.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mousecortexref.SeuratData_1.0.0 SeuratData_0.2.2.9002          
 [3] reticulate_1.42.0               RColorBrewer_1.1-3             
 [5] glmGamPoi_1.20.0                pheatmap_1.0.12                
 [7] patchwork_1.3.0                 Azimuth_0.5.0                  
 [9] shinyBS_0.61.1                  phateR_1.0.7                   
[11] Matrix_1.7-3                    Seurat_5.3.0                   
[13] SeuratObject_5.1.0              sp_2.2-0                       
[15] lubridate_1.9.4                 forcats_1.0.0                  
[17] stringr_1.5.1                   dplyr_1.1.4                    
[19] purrr_1.0.4                     readr_2.1.5                    
[21] tidyr_1.3.1                     tibble_3.2.1                   
[23] ggplot2_3.5.2                   tidyverse_2.0.0                

loaded via a namespace (and not attached):
  [1] fs_1.6.6                          ProtGenerics_1.40.0              
  [3] matrixStats_1.5.0                 spatstat.sparse_3.1-0            
  [5] bitops_1.0-9                      DirichletMultinomial_1.50.0      
  [7] TFBSTools_1.46.0                  httr_1.4.7                       
  [9] tools_4.5.0                       sctransform_0.4.1                
 [11] R6_2.6.1                          DT_0.33                          
 [13] lazyeval_0.2.2                    uwot_0.2.3                       
 [15] rhdf5filters_1.20.0               withr_3.0.2                      
 [17] gridExtra_2.3                     progressr_0.15.1                 
 [19] cli_3.6.5                         Biobase_2.68.0                   
 [21] spatstat.explore_3.4-2            fastDummies_1.7.5                
 [23] EnsDb.Hsapiens.v86_2.99.0         shinyjs_2.1.0                    
 [25] labeling_0.4.3                    sass_0.4.10                      
 [27] spatstat.data_3.1-6               ggridges_0.5.6                   
 [29] pbapply_1.7-2                     Rsamtools_2.24.0                 
 [31] dichromat_2.0-0.1                 parallelly_1.43.0                
 [33] BSgenome_1.76.0                   rstudioapi_0.17.1                
 [35] RSQLite_2.3.9                     generics_0.1.3                   
 [37] BiocIO_1.18.0                     gtools_3.9.5                     
 [39] ica_1.0-3                         spatstat.random_3.3-3            
 [41] googlesheets4_1.1.1               S4Vectors_0.46.0                 
 [43] abind_1.4-8                       lifecycle_1.0.4                  
 [45] yaml_2.3.10                       SummarizedExperiment_1.38.0      
 [47] rhdf5_2.52.0                      SparseArray_1.8.0                
 [49] Rtsne_0.17                        grid_4.5.0                       
 [51] blob_1.2.4                        promises_1.3.2                   
 [53] shinydashboard_0.7.3              crayon_1.5.3                     
 [55] pwalign_1.4.0                     miniUI_0.1.2                     
 [57] lattice_0.22-7                    beachmat_2.24.0                  
 [59] cowplot_1.1.3                     GenomicFeatures_1.60.0           
 [61] KEGGREST_1.48.0                   pillar_1.10.2                    
 [63] knitr_1.50                        GenomicRanges_1.60.0             
 [65] rjson_0.2.23                      future.apply_1.11.3              
 [67] codetools_0.2-20                  fastmatch_1.1-6                  
 [69] glue_1.8.0                        spatstat.univar_3.1-2            
 [71] data.table_1.17.0                 vctrs_0.6.5                      
 [73] png_0.1-8                         spam_2.11-1                      
 [75] cellranger_1.1.0                  gtable_0.3.6                     
 [77] cachem_1.1.0                      xfun_0.52                        
 [79] Signac_1.14.0                     S4Arrays_1.7.2                   
 [81] mime_0.13                         rsconnect_1.3.4                  
 [83] survival_3.8-3                    gargle_1.5.2                     
 [85] RcppRoll_0.3.1                    fitdistrplus_1.2-2               
 [87] ROCR_1.0-11                       nlme_3.1-168                     
 [89] bit64_4.6.0-1                     RcppAnnoy_0.0.22                 
 [91] GenomeInfoDb_1.44.0               bslib_0.9.0                      
 [93] irlba_2.3.5.1                     KernSmooth_2.23-26               
 [95] SeuratDisk_0.0.0.9021             colorspace_2.1-1                 
 [97] seqLogo_1.74.0                    BiocGenerics_0.54.0              
 [99] DBI_1.2.3                         tidyselect_1.2.1                 
[101] bit_4.6.0                         compiler_4.5.0                   
[103] curl_6.2.2                        hdf5r_1.3.12                     
[105] DelayedArray_0.34.1               plotly_4.10.4                    
[107] rtracklayer_1.68.0                scales_1.4.0                     
[109] caTools_1.18.3                    lmtest_0.9-40                    
[111] rappdirs_0.3.3                    digest_0.6.37                    
[113] goftest_1.2-3                     spatstat.utils_3.1-3             
[115] presto_1.0.0                      XVector_0.48.0                   
[117] htmltools_0.5.8.1                 pkgconfig_2.0.3                  
[119] MatrixGenerics_1.20.0             fastmap_1.2.0                    
[121] ensembldb_2.32.0                  rlang_1.1.6                      
[123] htmlwidgets_1.6.4                 UCSC.utils_1.4.0                 
[125] shiny_1.10.0                      jquerylib_0.1.4                  
[127] farver_2.1.2                      zoo_1.8-14                       
[129] jsonlite_2.0.0                    BiocParallel_1.42.0              
[131] RCurl_1.98-1.17                   magrittr_2.0.3                   
[133] GenomeInfoDbData_1.2.14           dotCall64_1.2                    
[135] Rhdf5lib_1.30.0                   Rcpp_1.0.14                      
[137] stringi_1.8.7                     MASS_7.3-65                      
[139] plyr_1.8.9                        parallel_4.5.0                   
[141] listenv_0.9.1                     ggrepel_0.9.6                    
[143] deldir_2.0-4                      Biostrings_2.76.0                
[145] splines_4.5.0                     tensor_1.5                       
[147] hms_1.1.3                         BSgenome.Hsapiens.UCSC.hg38_1.4.5
[149] igraph_2.1.4                      spatstat.geom_3.3-6              
[151] RcppHNSW_0.6.0                    reshape2_1.4.4                   
[153] stats4_4.5.0                      TFMPvalue_0.0.9                  
[155] XML_3.99-0.18                     evaluate_1.0.3                   
[157] JASPAR2020_0.99.10                tzdb_0.5.0                       
[159] httpuv_1.6.16                     RANN_2.6.2                       
[161] polyclip_1.10-7                   future_1.40.0                    
[163] scattermore_1.2                   xtable_1.8-4                     
[165] restfulr_0.0.15                   AnnotationFilter_1.32.0          
[167] RSpectra_0.16-2                   later_1.4.2                      
[169] viridisLite_0.4.2                 googledrive_2.1.1                
[171] memoise_2.0.1                     AnnotationDbi_1.70.0             
[173] GenomicAlignments_1.44.0          IRanges_2.42.0                   
[175] cluster_2.1.8.1                   timechange_0.3.0                 
[177] globals_0.17.0
```

**Comment by sameet** [comment]
The downgrade to `5.2.1` works.

**Comment by BenjaminDEMAILLE** [comment]
> The downgrade to `5.2.1` works.

not for me. Did you got the same ? #9866

**Comment by BenjaminDEMAILLE** [comment]
> I have tried this with `5.0.2`, `5.2.0`, and `5.2.1`, and it works on all three. It definitely fails on `5.3.0`.

My object is 
```r 
An object of class Seurat 
157441 features across 86390 samples within 5 assays 
Active assay: SCT (22657 features, 3000 variable features)
 3 layers present: counts, data, scale.data
 4 other assays present: RNA, spliced, unspliced, original.counts
 7 dimensional reductions calculated: pca, integrated.rpca, integrated.cca, harmony, umap.rpca, umap.cca, umap.harmony
```

Can it be linked to?

**Comment by zskylarli** [comment]
Hello! This bug has been fixed in the latest development version of Seurat (v.5.3.1); please reinstall Seurat from our GitHub repository (the main branch) and let me know if the error arises again. Thanks!

**Comment by Mridul-Chaudhary** [comment]
Thanks.. Downgrading Seurat to 5.2.1 from 5.3.0 removed the error!

**Comment by rabiafidan** [comment]
> Hello! This bug has been fixed in the latest development version of Seurat (v.5.3.1); please reinstall Seurat from our GitHub repository (the main branch) and let me know if the error arises again. Thanks!

Hi @zskylarli  I am still failing to run Azimuth on Seurat v5.3.1
```
> #run Azimuth
> merged_seurat_normal_filtered <- RunAzimuth(merged_seurat_normal_filtered, reference = "kidneyref")
Warning: Overwriting miscellanous data for model
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
detected inputs from HUMAN with id type Gene.name
reference rownames detected HUMAN with id type Gene.name
Error in ValidateParams_FindTransferAnchors(reference = reference, query = query,  : 
  Reference assay is SCT, but query assay is RNA. Mixing SCT and non-SCT in FindTransferAnchors is not supported.
```
```
> sessionInfo()
R version 4.5.0 (2025-04-11)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices datasets  utils     methods  
[8] base     

other attached packages:
 [1] scDblFinder_1.22.0          SingleCellExperiment_1.30.1
 [3] scCustomize_3.0.1           devtools_2.4.5             
 [5] usethis_3.1.0               speckle_1.8.0              
 [7] DESeq2_1.48.1               SummarizedExperiment_1.38.1
 [9] MatrixGenerics_1.20.0       matrixStats_1.5.0          
[11] GenomicRanges_1.60.0        GenomeInfoDb_1.44.0        
[13] IRanges_2.42.0              S4Vectors_0.46.0           
[15] fgsea_1.34.0                CellChat_2.2.0             
[17] Biobase_2.68.0              BiocGenerics_0.54.0        
[19] generics_0.1.4              igraph_2.1.4               
[21] Azimuth_0.5.0               shinyBS_0.61.1             
[23] limma_3.64.1                ggpubr_0.6.1               
[25] gprofiler2_0.2.3            BiocManager_1.30.26        
[27] msigdbr_25.1.0              patchwork_1.3.1            
[29] harmony_1.2.3               Rcpp_1.1.0                 
[31] lubridate_1.9.4             forcats_1.0.0              
[33] stringr_1.5.1               dplyr_1.1.4                
[35] purrr_1.1.0                 readr_2.1.5                
[37] tidyr_1.3.1                 tibble_3.3.0               
[39] ggplot2_3.5.2               tidyverse_2.0.0            
[41] Seurat_5.3.1.0000           SeuratObject_5.1.0         
[43] sp_2.2-0                   

loaded via a namespace (and not attached):
  [1] urlchecker_1.0.1                  goftest_1.2-3                    
  [3] DT_0.33                           Biostrings_2.76.0                
  [5] kidneyref.SeuratData_1.0.2        vctrs_0.6.5                      
  [7] spatstat.random_3.4-1             digest_0.6.37                    
  [9] png_0.1-8                         shape_1.4.6.1                    
 [11] registry_0.5-1                    ggrepel_0.9.6                    
 [13] deldir_2.0-4                      parallelly_1.45.0                
 [15] renv_1.1.4                        MASS_7.3-65                      
 [17] Signac_1.14.0                     reshape2_1.4.4                   
 [19] httpuv_1.6.16                     foreach_1.5.2                    
 [21] withr_3.0.2                       ggrastr_1.0.2                    
 [23] ellipsis_0.3.2                    survival_3.8-3                   
 [25] EnsDb.Hsapiens.v86_2.99.0         memoise_2.0.1                    
 [27] ggbeeswarm_0.7.2                  janitor_2.2.1                    
 [29] profvis_0.4.0                     systemfonts_1.2.3                
 [31] zoo_1.8-14                        GlobalOptions_0.1.2              
 [33] gtools_3.9.5                      pbapply_1.7-2                    
 [35] Formula_1.2-5                     rematch2_2.1.2                   
 [37] KEGGREST_1.48.1                   promises_1.3.3                   
 [39] httr_1.4.7                        rstatix_0.7.2                    
 [41] restfulr_0.0.16                   globals_0.18.0                   
 [43] fitdistrplus_1.2-4                rhdf5filters_1.20.0              
 [45] ps_1.9.1                          rstudioapi_0.17.1                
 [47] rhdf5_2.52.1                      UCSC.utils_1.4.0                 
 [49] miniUI_0.1.2                      processx_3.8.6                   
 [51] ggalluvial_0.12.5                 babelgene_22.9                   
 [53] curl_6.4.0                        ScaledMatrix_1.16.0              
 [55] polyclip_1.10-7                   GenomeInfoDbData_1.2.14          
 [57] SparseArray_1.8.0                 desc_1.4.3                       
 [59] xtable_1.8-4                      doParallel_1.0.17                
 [61] S4Arrays_1.8.1                    hms_1.1.3                        
 [63] irlba_2.3.5.1                     colorspace_2.1-1                 
 [65] hdf5r_1.3.12                      ggnetwork_0.5.13                 
 [67] ROCR_1.0-11                       reticulate_1.42.0                
 [69] spatstat.data_3.1-6               snakecase_0.11.1                 
 [71] magrittr_2.0.3                    lmtest_0.9-40                    
 [73] viridis_0.6.5                     later_1.4.2                      
 [75] lattice_0.22-7                    spatstat.geom_3.4-1              
 [77] NMF_0.28                          future.apply_1.20.0              
 [79] scuttle_1.18.0                    scattermore_1.2                  
 [81] XML_3.99-0.18                     cowplot_1.2.0                    
 [83] RcppAnnoy_0.0.22                  pillar_1.11.0                    
 [85] nlme_3.1-168                      iterators_1.0.14                 
 [87] sna_2.8                           pwalign_1.4.0                    
 [89] beachmat_2.24.0                   gridBase_0.4-7                   
 [91] caTools_1.18.3                    compiler_4.5.0                   
 [93] RSpectra_0.16-2                   stringi_1.8.7                    
 [95] tensor_1.5.1                      GenomicAlignments_1.44.0         
 [97] plyr_1.8.9                        scater_1.36.0                    
 [99] crayon_1.5.3                      abind_1.4-8                      
[101] BiocIO_1.18.0                     googledrive_2.1.1                
[103] locfit_1.5-9.12                   bit_4.6.0                        
[105] fastmatch_1.1-6                   textshaping_1.0.1                
[107] codetools_0.2-20                  BiocSingular_1.24.0              
[109] bslib_0.9.0                       paletteer_1.6.0                  
[111] SeuratData_0.2.2.9002             GetoptLong_1.0.5                 
[113] plotly_4.11.0                     mime_0.13                        
[115] splines_4.5.0                     circlize_0.4.16                  
[117] fastDummies_1.7.5                 cellranger_1.1.0                 
[119] blob_1.2.4                        clue_0.3-66                      
[121] seqLogo_1.74.0                    AnnotationFilter_1.32.0          
[123] fs_1.6.6                          listenv_0.9.1                    
[125] pkgbuild_1.4.8                    ggsignif_0.6.4                   
[127] Matrix_1.7-3                      callr_3.7.6                      
[129] statmod_1.5.0                     svglite_2.2.1                    
[131] tzdb_0.5.0                        pkgconfig_2.0.3                  
[133] network_1.19.0                    tools_4.5.0                      
[135] cachem_1.1.0                      RSQLite_2.4.1                    
[137] viridisLite_0.4.2                 DBI_1.2.3                        
[139] fastmap_1.2.0                     scales_1.4.0                     
[141] grid_4.5.0                        ica_1.0-3                        
[143] shinydashboard_0.7.3              Rsamtools_2.24.0                 
[145] broom_1.0.8                       sass_0.4.10                      
[147] coda_0.19-4.1                     FNN_1.1.4.1                      
[149] ggprism_1.0.6                     dotCall64_1.2                    
[151] carData_3.0-5                     RANN_2.6.2                       
[153] farver_2.1.2                      yaml_2.3.10                      
[155] rtracklayer_1.68.0                cli_3.6.5                        
[157] lifecycle_1.0.4                   uwot_0.2.3                       
[159] bluster_1.18.0                    sessioninfo_1.2.3                
[161] presto_1.0.0                      backports_1.5.0                  
[163] BSgenome.Hsapiens.UCSC.hg38_1.4.5 BiocParallel_1.42.1              
[165] timechange_0.3.0                  gtable_0.3.6                     
[167] rjson_0.2.23                      ggridges_0.5.6                   
[169] progressr_0.15.1                  parallel_4.5.0                   
[171] edgeR_4.6.2                       jsonlite_2.0.0                   
[173] RcppHNSW_0.6.0                    TFBSTools_1.46.0                 
[175] bitops_1.0-9                      xgboost_1.7.11.1                 
[177] bit64_4.6.0-1                     assertthat_0.2.1                 
[179] Rtsne_0.17                        spatstat.utils_3.1-5             
[181] BiocNeighbors_2.2.0               metapod_1.16.0                   
[183] jquerylib_0.1.4                   dqrng_0.4.1                      
[185] shinyjs_2.1.0                     SeuratDisk_0.0.0.9021            
[187] spatstat.univar_3.1-4             lazyeval_0.2.2                   
[189] shiny_1.11.1                      htmltools_0.5.8.1                
[191] sctransform_0.4.2                 rappdirs_0.3.3                   
[193] ensembldb_2.32.0                  glue_1.8.0                       
[195] TFMPvalue_0.0.9                   spam_2.11-1                      
[197] googlesheets4_1.1.1               XVector_0.48.0                   
[199] RCurl_1.98-1.17                   scran_1.36.0                     
[201] BSgenome_1.76.0                   gridExtra_2.3                    
[203] JASPAR2020_0.99.10                R6_2.6.1                         
[205] RcppRoll_0.3.1                    GenomicFeatures_1.60.0           
[207] cluster_2.1.8.1                   rngtools_1.5.2                   
[209] pkgload_1.4.0                     Rhdf5lib_1.30.0                  
[211] gargle_1.5.2                      statnet.common_4.12.0            
[213] DirichletMultinomial_1.50.0       vipor_0.4.7                      
[215] DelayedArray_0.34.1               tidyselect_1.2.1                 
[217] ProtGenerics_1.40.0               car_3.1-3                        
[219] AnnotationDbi_1.70.0              future_1.58.0                    
[221] rsvd_1.0.5                        KernSmooth_2.23-26               
[223] data.table_1.17.8                 htmlwidgets_1.6.4                
[225] ComplexHeatmap_2.24.1             RColorBrewer_1.1-3               
[227] rlang_1.1.6                       spatstat.sparse_3.1-0            
[229] spatstat.explore_3.4-3            remotes_2.5.0                    
[231] beeswarm_0.4.0  
```

**Comment by rabiafidan** [comment]
This is fixed now. See:
https://github.com/satijalab/seurat/issues/10032#issuecomment-3151814497
